'use client';
import {useEffect,useState,type FormEvent} from 'react';

export default function ResetPasswordForm(){
 const [valid,setValid]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{void fetch('/api/auth/recover',{cache:'no-store'}).then(async response=>{const data=await response.json();setValid(response.ok&&data.valid===true);}).catch(()=>setValid(false));},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError('');const form=new FormData(event.currentTarget),password=String(form.get('password')??''),confirmation=String(form.get('confirmation')??'');if(password!==confirmation){setError('새 비밀번호가 서로 다릅니다.');setBusy(false);return;}try{const response=await fetch('/api/auth/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update',password})}),data=await response.json();if(!response.ok)throw new Error(data.error??'비밀번호를 변경하지 못했습니다.');location.assign('/login?password_reset=success');}catch(e){setError(e instanceof Error?e.message:'복구 링크를 다시 요청해주세요.');setBusy(false);}}
 return <><link rel="stylesheet" href="/one/fonts/pretendard.css" precedence="login"/><main className="nh-login"><div className="nh-login-card"><a href="/login" className="nh-wordmark"><img src="/brand/nuri-one.svg" alt="NURI ONE" width="8541" height="1600"/></a><h1>비밀번호 재설정</h1>{valid===null?<p role="status">복구 링크를 확인하고 있습니다.</p>:!valid?<><p role="alert">복구 링크가 만료되었거나 이미 사용되었습니다. 비밀번호 찾기에서 다시 요청해주세요.</p><a href="/login">로그인으로 돌아가기</a></>:<form onSubmit={submit} aria-busy={busy}><div className="nh-login-field"><label htmlFor="reset-password">새 비밀번호</label><input id="reset-password" name="password" type="password" autoComplete="new-password" minLength={12} maxLength={200} required/></div><div className="nh-login-field"><label htmlFor="reset-confirmation">새 비밀번호 확인</label><input id="reset-confirmation" name="confirmation" type="password" autoComplete="new-password" minLength={12} maxLength={200} required/></div><button type="submit" className="nh-login-submit" disabled={busy}>{busy?'변경 중…':'비밀번호 변경'}</button>{error&&<p role="alert" className="nh-login-message is-error">{error}</p>}</form>}</div></main></>;
}
