import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {createHash} from 'node:crypto';
import {NextRequest} from 'next/server';
import {seal,unseal} from '../src/lib/security';
import {GET as authStatus,POST as login,DELETE as authLogout} from '../src/app/api/auth/route';
import {GET as authCallback} from '../src/app/api/auth/callback/route';
import {GET as recoveryStatus,POST as recover} from '../src/app/api/auth/recover/route';
import {GET as accessList,POST as review} from '../src/app/api/access/route';
import {GET as operations,POST as configure} from '../src/app/api/operations/route';
import {GET as dashboard,POST as mutate} from '../src/app/api/dashboard/[...route]/route';
import {accessStatus,isOwner} from '../src/lib/auth';

test('portal separation, owner approvals, read-only access and immediate revocation',async()=>{
 const db=new PGlite(),previousFetch=globalThis.fetch,global=globalThis as typeof globalThis&{nhPool?:unknown},previousPool=global.nhPool,previousEnv={...process.env};
 const owner={id:'00000000-0000-4000-8000-000000000001',email:'owner@example.invalid',email_confirmed_at:new Date().toISOString()},viewer={id:'00000000-0000-4000-8000-000000000002',email:'viewer@example.invalid',email_confirmed_at:new Date().toISOString(),user_metadata:{role:'owner',approved:true}},origin='http://127.0.0.1:3120';
 const query=async(sql:string,args:unknown[]=[])=>{if(sql.startsWith('SELECT pg_advisory_xact_lock'))return {rows:[],rowCount:1};const result=await db.query(sql,args);return {...result,rowCount:result.affectedRows??result.rows.length};};let aliasLogoutRequests=0;
 try{
  await db.exec((await readFile('db/dashboard.sql','utf8')).split('ALTER TABLE')[0]);
  global.nhPool={query,connect:async()=>({query,release(){}})};
  Object.assign(process.env,{DATABASE_URL:'postgres://test-only',MARKET_MODE:'test',MARKET_ORIGIN:origin,SUPABASE_URL:'https://auth.example.invalid',SUPABASE_PUBLISHABLE_KEY:'test-only',SUPABASE_SERVICE_ROLE_KEY:'test-only',SESSION_SECRET:'test-only-security-check-secret-32-characters',OPERATOR_EMAIL:owner.email,OPERATOR_USER_ID:owner.id});
  globalThis.fetch=async(input,init)=>{const url=String(input);if(url.startsWith('https://naverapihub.apigw.ntruss.com/')){assert.equal(new Headers(init?.headers).get('X-NCP-APIGW-API-KEY'),'private-naver-key');return Response.json({items:[{title:'공식 행사',link:'https://example.invalid/event'}]});}assert(url.startsWith('https://auth.example.invalid/auth/v1/'),'No real network calls permitted');const headers=new Headers(init?.headers),token=headers.get('Authorization'),user=token==='Bearer owner-token'?owner:viewer;
   if(url.includes('/token?')){const value=JSON.parse(String(init?.body));return Response.json({access_token:value.email===owner.email?'owner-token':'viewer-token',refresh_token:'test-refresh',expires_in:3600});}
   if(url.endsWith('/admin/users/'+viewer.id))return Response.json(viewer);
   if(url.endsWith('/user'))return Response.json(user);
   if(url.endsWith('/logout?scope=local')){aliasLogoutRequests++;return new Response(null,{status:204});}
   throw new Error('Unexpected authentication call');
  };
  const req=(path:string,token='',payload?:unknown)=>new NextRequest(origin+path,{method:payload?'POST':'GET',headers:{Origin:origin,...(token?{Cookie:'nh_access='+token}:{}),'Content-Type':'application/json'},...(payload?{body:JSON.stringify(payload)}:{})});
  const attempt=(portal:'one'|'market')=>login(req('/api/auth','',{action:'login',email:viewer.email,password:'secure-test-password',portal}));
  const ctx={params:Promise.resolve({route:['state']})};
  assert.equal(isOwner(viewer),false);assert.equal(isOwner({...owner,email_confirmed_at:undefined}),false);
  const secondOperator={id:'00000000-0000-4000-8000-000000000003',email:'zero@example.invalid',email_confirmed_at:new Date().toISOString()};
  assert.equal(isOwner(secondOperator),false);Object.assign(process.env,{SECOND_OPERATOR_USER_ID:secondOperator.id,SECOND_OPERATOR_EMAIL:secondOperator.email});assert.equal(isOwner(secondOperator),true);
  for(const candidate of [{...secondOperator,email:viewer.email},{...secondOperator,id:viewer.id},{...secondOperator,email_confirmed_at:undefined},{...secondOperator,is_anonymous:true}])assert.equal(isOwner(candidate),false,'secondary operator requires the trusted ID/email pair and confirmed identity');
  process.env.SECOND_OPERATOR_EMAIL='';assert.equal(isOwner(secondOperator),false);delete process.env.SECOND_OPERATOR_USER_ID;delete process.env.SECOND_OPERATOR_EMAIL;
  assert.equal((await dashboard(req('/api/dashboard/state'),ctx)).status,401);
  assert.equal((await accessList(req('/api/access','viewer-token'))).status,403);
  assert.equal((await (await attempt('market')).json()).destination,'/nurimarket');assert.equal(await accessStatus(viewer),'none');
  const pending=await attempt('one');assert.equal(pending.status,200);assert.equal((await pending.json()).destination,'/access-pending');assert.match(pending.headers.get('set-cookie')??'',/HttpOnly/);assert.equal(await accessStatus(viewer),'pending');
  assert.equal((await dashboard(req('/api/dashboard/state','viewer-token'),ctx)).status,403);
  const list=await (await accessList(req('/api/access','owner-token'))).json(),initial=list.requests[0];assert.equal(initial.email,viewer.email);
  const approval=await review(req('/api/access','owner-token',{id:viewer.id,action:'approve',version:initial.version}));assert.equal(approval.status,200);const approved=(await approval.json()).request;
  assert.equal((await review(req('/api/access','owner-token',{id:viewer.id,action:'deny',version:initial.version}))).status,409);
  assert.equal((await (await attempt('one')).json()).destination,'/dashboard');assert.equal((await (await attempt('market')).json()).destination,'/nurimarket');
  await db.query("INSERT INTO nh_documents(workspace,kind,id,data) VALUES('live','login-id','zero',$1)",[JSON.stringify({userId:viewer.id,email:viewer.email})]);
  const aliasAttempt=(email:string,portal='one',action='login')=>login(req('/api/auth','',{action,email,password:'secure-test-password',portal}));
  const aliasLogin=await aliasAttempt(' ZERO ');assert.equal(aliasLogin.status,200);assert.deepEqual(await aliasLogin.json(),{destination:'/dashboard',owner:false,readOnly:true,access:'approved'},'login ID keeps the existing verified identity and permissions');
  const unknownAlias=await aliasAttempt('unregistered');assert.equal(unknownAlias.status,400);const unknownError=(await unknownAlias.json()).error;assert.equal((await aliasAttempt('zero','market')).status,400);assert.equal((await aliasAttempt('zero','one','signup')).status,400,'IDs do not replace verified signup emails');
  await db.query("UPDATE nh_documents SET data=$1 WHERE workspace='live' AND kind='login-id' AND id='zero'",[JSON.stringify({userId:owner.id,email:viewer.email})]);
  const mismatchedAlias=await aliasAttempt('zero');assert.equal(mismatchedAlias.status,400);assert.equal((await mismatchedAlias.json()).error,unknownError);assert.equal(mismatchedAlias.cookies.get('nh_access'),undefined,'email reassignment or mismatched auth ID cannot grant access');assert.equal(aliasLogoutRequests,1,'rejected provider session is logged out');
  const session=await (await dashboard(req('/api/dashboard/session','viewer-token'),{params:Promise.resolve({route:['session']})})).json();assert.equal(session.owner,false);assert.equal(session.readOnly,true);
  await db.query("INSERT INTO nh_documents(workspace,kind,id,data) VALUES('live','channel','fixture',$1)",[JSON.stringify({label:'공개 계정',service:'market',channel:'x',username:'public-handle',verifiedAt:'2026-10-07',loginUsername:'private-login',token:'private-token'})]);
  const view=await dashboard(req('/api/dashboard/state','viewer-token'),ctx);assert.equal(view.status,200);const state=await view.json();assert.deepEqual(state.accounts,[{id:'fixture',label:'공개 계정',service:'market',channel:'x',username:'public-handle',verifiedAt:'2026-10-07'}]);assert.deepEqual(state.aiConfig,{});assert.deepEqual(state.naver,{});assert.deepEqual(state.audit,[]);
  assert.equal((await operations(req('/api/operations','viewer-token'))).status,403);assert.equal((await configure(req('/api/operations','viewer-token',{action:'smtp-draft'}))).status,403);
  for(const route of ['naver/config','naver/research','refresh','money','ai','ownership','publishing/settings','sample/refresh','studio/preview','studio/manual','studio/repurpose','studio/restore','growth/campaign','growth/result','content/platform-exclusion'])assert.equal((await mutate(req('/api/dashboard/'+route,'viewer-token',{}),{params:Promise.resolve({route:route.split('/')})})).status,403);
  const naverCall=async(route:string,payload:unknown,status=200)=>{const response=await mutate(req('/api/dashboard/naver/'+route,'owner-token',payload),{params:Promise.resolve({route:['naver',route]})}),body=await response.json();assert.equal(response.status,status,JSON.stringify(body));assert(!JSON.stringify(body).includes('private-naver-'),'keys never appear in state/errors');return body;};
  await naverCall('research',{mode:'news',query:'행사'},400);
  const saved=await naverCall('config',{version:1,appName:'nurione',apiKeyId:'private-naver-id',apiKey:'private-naver-key'});assert.equal(saved.naver.configured,true);assert.equal(saved.naver.version,2);assert.equal(saved.naver.report,null);
  const stored=(await db.query<{data:{secret:string}}>("SELECT data FROM nh_documents WHERE workspace='live' AND kind='naver' AND id='config'")).rows[0].data;assert(!JSON.stringify(stored).includes('private-naver-'),'DB credentials encrypted');
  await naverCall('config',{version:1,apiKeyId:'other',apiKey:'other'},409);
  const researched=await naverCall('research',{mode:'news',query:'행사'});assert.equal(researched.naver.report.items[0].title,'공식 행사');assert.deepEqual((await (await dashboard(req('/api/dashboard/state','viewer-token'),ctx)).json()).naver,{});
  const kept=await naverCall('config',{version:2,appName:'nurione'});assert.equal(kept.naver.version,3);assert.equal(kept.naver.report,null);await naverCall('research',{mode:'news',query:'다음 행사'});
  const crossSite=req('/api/dashboard/naver/config','owner-token',{version:3,appName:'bad'});crossSite.headers.set('Origin','https://evil.invalid');assert.equal((await mutate(crossSite,{params:Promise.resolve({route:['naver','config']})})).status,403);
  const publishingInput={timezone:'Asia/Seoul',dailyCount:5,times:['08:00','12:00','16:00','20:00','22:00'],enabled:false,version:1,service:'facebook',account:'attacker-account',business:'attacker-business'},publishRoute={params:Promise.resolve({route:['publishing','settings']})};assert.equal((await mutate(req('/api/dashboard/publishing/settings','owner-token',publishingInput),publishRoute)).status,200);const persistedSettings=(await (await dashboard(req('/api/dashboard/state','owner-token'),ctx)).json() as {publishingSettings:{timezone:string;dailyCount:number;times:string[];enabled:boolean;version:number;updatedAt:string}}).publishingSettings;assert.deepEqual({timezone:persistedSettings.timezone,dailyCount:persistedSettings.dailyCount,times:persistedSettings.times,enabled:persistedSettings.enabled,version:persistedSettings.version},{timezone:'Asia/Seoul',dailyCount:5,times:publishingInput.times,enabled:false,version:2});assert.match(persistedSettings.updatedAt,/./);assert.equal((await db.query<{id:string}>("SELECT id FROM nh_documents WHERE workspace='live' AND kind='publishing-settings'")).rows[0].id,'tistory','request cannot redirect the singleton setting to another service or account');assert.equal((await mutate(req('/api/dashboard/publishing/settings','owner-token',publishingInput),publishRoute)).status,409,'stale settings version is rejected');
  const environment=process.env.NODE_ENV;Object.assign(process.env,{NODE_ENV:'production'});assert.equal((await dashboard(req('/api/dashboard/sample/state','owner-token'),{params:Promise.resolve({route:['sample','state']})})).status,404);if(environment===undefined)Reflect.deleteProperty(process.env,'NODE_ENV');else Object.assign(process.env,{NODE_ENV:environment});
  assert.equal((await review(req('/api/access','viewer-token',{id:viewer.id,action:'approve',version:approved.version}))).status,403);
  const oldEmail=viewer.email;viewer.email='changed@example.invalid';assert.equal(await accessStatus(viewer),'none');assert.equal((await review(req('/api/access','owner-token',{id:viewer.id,action:'revoke',version:approved.version}))).status,409);viewer.email=oldEmail;
  const revoked=await review(req('/api/access','owner-token',{id:viewer.id,action:'revoke',version:approved.version}));assert.equal(revoked.status,200);
  assert.equal((await dashboard(req('/api/dashboard/state','viewer-token'),ctx)).status,403);assert.equal((await (await authStatus(req('/api/auth?portal=one','viewer-token'))).json()).access,'revoked');
  await attempt('one');assert.equal(await accessStatus(viewer),'revoked');assert.equal((await db.query("SELECT * FROM nh_audit WHERE action='access.requested'")).rows.length,1);viewer.email='new-confirmed@example.invalid';await attempt('one');assert.equal(await accessStatus(viewer),'pending');assert.equal((await accessList(req('/api/access','owner-token')).then(r=>r.json())).requests[0].email,viewer.email);
 }finally{globalThis.fetch=previousFetch;global.nhPool=previousPool;for(const key of Object.keys(process.env))if(!(key in previousEnv))delete process.env[key];Object.assign(process.env,previousEnv);await db.close();}
});

test('email login preserves short existing passwords and recovery is PKCE-bound, expiring, single-use and secret-safe',async()=>{
 const db=new PGlite(),previousFetch=globalThis.fetch,g=globalThis as typeof globalThis&{nhPool?:unknown},previousPool=g.nhPool,previousEnv={...process.env},origin='https://auth.example.invalid';const owner={id:'00000000-0000-4000-8000-000000000001',email:'owner@example.invalid',email_confirmed_at:new Date().toISOString()};let challenge='',recoveryRequests=0,passwordUpdates=0,updatedPassword='',logoutFails=true,recoveryMailFails=false;
 const query=async(sql:string,args:unknown[]=[])=>{const result=await db.query(sql,args);return {...result,rowCount:result.affectedRows??result.rows.length};};
 try{await db.exec((await readFile('db/dashboard.sql','utf8')).split('ALTER TABLE')[0]);g.nhPool={query,connect:async()=>({query,release(){}})};Object.assign(process.env,{DATABASE_URL:'postgres://test-only',MARKET_MODE:'test',MARKET_ORIGIN:origin,SUPABASE_URL:'https://auth.example.invalid',SUPABASE_PUBLISHABLE_KEY:'test-only',SESSION_SECRET:'test-only-recovery-cookie-key-32-characters',OPERATOR_EMAIL:owner.email,OPERATOR_USER_ID:owner.id});
  globalThis.fetch=async(input,init)=>{const url=String(input),method=init?.method??'GET',headers=new Headers(init?.headers);assert(url.startsWith('https://auth.example.invalid/auth/v1/'),'No external provider calls in recovery test');if(url.includes('/recover?redirect_to=')){recoveryRequests++;const value=JSON.parse(String(init?.body));challenge=value.code_challenge;assert.equal(value.code_challenge_method,'s256');assert.equal(new URL(url).searchParams.get('redirect_to'),origin+'/api/auth/callback');return recoveryMailFails?Response.json({message:'provider unavailable'},{status:500}):Response.json({});}if(url.includes('/token?grant_type=pkce')){const value=JSON.parse(String(init?.body));if(value.auth_code==='google-flow-code'&&value.code_verifier==='g'.repeat(43))return Response.json({access_token:'google-test-access',refresh_token:'google-test-refresh',expires_in:3600});if(value.auth_code==='recovery-code'&&createHash('sha256').update(value.code_verifier).digest('base64url')===challenge)return Response.json({access_token:'recovery-test-access',refresh_token:'must-not-be-set',expires_in:3600});return Response.json({message:'invalid verifier'},{status:400});}if(url.includes('/token?grant_type=password'))return Response.json({access_token:'owner-test-access',refresh_token:'owner-test-refresh',expires_in:3600});if(url.endsWith('/logout?scope=local'))return logoutFails?Response.json({message:'provider unavailable'},{status:503}):Response.json({});if(url.endsWith('/user')&&method==='PUT'){passwordUpdates++;updatedPassword=JSON.parse(String(init?.body)).password;return Response.json({});}if(url.endsWith('/user')&&headers.get('Authorization')?.startsWith('Bearer '))return Response.json(owner);throw new Error('Unexpected test auth request');};
  const request=(path:string,method='GET',payload?:unknown,cookie='')=>new NextRequest(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(payload===undefined?{}:{body:JSON.stringify(payload)})});
  const oldPassword=await login(request('/api/auth','POST',{action:'login',portal:'one',email:owner.email,password:'a'}));assert.equal(oldPassword.status,200,'existing short password can authenticate');const loginCookie=oldPassword.headers.get('set-cookie')??'';assert.match(loginCookie,/HttpOnly/);assert.match(loginCookie,/Secure/);assert.match(loginCookie,/SameSite=lax/i);
  assert.equal((await login(request('/api/auth','POST',{action:'signup',portal:'one',email:owner.email,password:'short'}))).status,400,'new accounts retain the 12-character minimum');
  const sent=await recover(request('/api/auth/recover','POST',{action:'request',email:owner.email}));assert.equal(sent.status,200);assert.match((await sent.json()).message,/해당 이메일이 등록되어 있다면/);assert.equal(recoveryRequests,1);const flowCookie=sent.cookies.get('nh_password_recovery_flow')!.value;assert.match(sent.headers.get('set-cookie')!,/HttpOnly/);assert.match(sent.headers.get('set-cookie')!,/Secure/);assert(!sent.headers.get('set-cookie')!.includes('code_verifier'));const expiredFlow=JSON.parse(unseal(flowCookie));expiredFlow.expires=Date.now()-1;const expired=await authCallback(request('/api/auth/callback?code=expired-code','GET',undefined,'nh_password_recovery_flow='+seal(JSON.stringify(expiredFlow))));assert.equal(expired.headers.get('location'),origin+'/login?error=recovery_failed');
   const googleFlow=seal(JSON.stringify({verifier:'g'.repeat(43),portal:'one',expires:Date.now()+600000}));const coexist='nh_password_recovery_flow='+flowCookie+'; nh_oauth='+googleFlow;const google=await authCallback(request('/api/auth/callback?code=google-flow-code','GET',undefined,coexist));assert.equal(google.headers.get('location'),origin+'/dashboard');assert(google.cookies.get('nh_access'),'Google login still completes');assert.match(google.headers.get('set-cookie')!,/nh_oauth=.*Max-Age=0/);assert(!google.headers.get('set-cookie')!.includes('nh_password_recovery_flow='),'Google callback preserves pending recovery flow');
   const callback=await authCallback(request('/api/auth/callback?code=recovery-code','GET',undefined,'nh_password_recovery_flow='+flowCookie));assert.equal(callback.headers.get('location'),origin+'/reset-password');const sessionCookie=callback.cookies.get('nh_password_recovery_session')!.value;assert.equal((JSON.parse(unseal(sessionCookie)) as {purpose:string}).purpose,'password-recovery-session');assert.equal(Number((await db.query<{count:number}>("SELECT count(*) AS count FROM nh_documents WHERE workspace='live' AND kind='password-recovery'")).rows[0].count),1);assert(!callback.cookies.get('nh_access'),'recovery does not create a normal login session');assert(!callback.headers.get('set-cookie')!.includes('recovery-test-access'),'recovery access token stays encrypted in HttpOnly cookie');
   const check=await recoveryStatus(request('/api/auth/recover','GET',undefined,'nh_password_recovery_session='+sessionCookie)),checkData=await check.json() as {valid?:boolean};assert.equal(check.status,200,JSON.stringify(checkData));assert.equal(checkData.valid,true,JSON.stringify(checkData));
  assert.equal((await recover(request('/api/auth/recover','POST',{action:'update',password:'12345678901'},'nh_password_recovery_session='+sessionCookie))).status,400);assert.equal(passwordUpdates,0);
  const updated=await recover(request('/api/auth/recover','POST',{action:'update',password:' 1234567890 '},'nh_password_recovery_session='+sessionCookie));assert.equal(updated.status,200);assert.equal(passwordUpdates,1);assert.equal(updatedPassword,' 1234567890 ','recovery must pass the exact password, including surrounding spaces');assert.match(updated.headers.get('set-cookie')!,/Max-Age=0/);
   assert.equal((await recover(request('/api/auth/recover','POST',{action:'update',password:'123456789012'},'nh_password_recovery_session='+sessionCookie))).status,401,'successful recovery nonce is consumed');const unknownEmail=await recover(request('/api/auth/recover','POST',{action:'request',email:'unregistered@example.invalid'}));assert.equal(unknownEmail.status,200);assert.equal((await unknownEmail.json()).message,'해당 이메일이 등록되어 있다면 비밀번호 복구 링크를 보냈습니다. 메일함을 확인해주세요.','unknown addresses receive the same public response');recoveryMailFails=true;const smtpFailure=await recover(request('/api/auth/recover','POST',{action:'request',email:owner.email}));assert.equal(smtpFailure.status,503);assert.match((await smtpFailure.json()).error,/Supabase 이메일 provider와 SMTP 설정/);
  const logout=await authLogout(request('/api/auth','DELETE',undefined,'nh_access=owner-test-access'));assert.equal(logout.status,503);assert.deepEqual(await logout.json(),{ok:false,localCleared:true,error:'이 기기의 로그아웃은 완료했지만 인증 서버 세션 종료를 확인하지 못했습니다.'});assert.match(logout.headers.get('set-cookie')!,/nh_access=.*Max-Age=0.*Secure/);logoutFails=false;assert.equal((await authLogout(request('/api/auth','DELETE',undefined,'nh_access=owner-test-access')).then(r=>r.json())).ok,true);
 }finally{globalThis.fetch=previousFetch;g.nhPool=previousPool;for(const key of Object.keys(process.env))if(!(key in previousEnv))delete process.env[key];Object.assign(process.env,previousEnv);await db.close();}
});
