import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {NextRequest} from 'next/server';
import {POST as connect,GET as callback} from '../src/app/api/adsense/route';
import {POST as dashboard,GET as dashboardGet} from '../src/app/api/dashboard/[...route]/route';
import {context} from '../src/server/context.cjs';
import {scope,parseReport,parsePayments} from '../src/server/adsense.cjs';
import {unseal,seal} from '../src/lib/security';
import vm from 'node:vm';

test('AdSense owner/session-bound one-time OAuth, fixed hosts, encrypted tokens, explicit account and isolated honest reports',async()=>{
 const db=new PGlite(),priorEnv={...process.env},priorFetch=globalThis.fetch,g=globalThis as typeof globalThis&{nhPool?:unknown},priorPool=g.nhPool;
 const origin='https://nuri.example.invalid',owner={id:'adsense-owner',email:'owner@example.invalid',email_confirmed_at:'2026-10-08'},viewer={...owner,id:'viewer'},account='accounts/pub-4637265976541550',other='accounts/pub-6018943099120763';let current=owner,apiCalls=0,refreshCalls=0,reportMode='ok',paymentsFail=false,tokenFail=false;
 const sessionId='6d41a99a-a317-45d5-8c41-b031ca1eef6a',claims=(payload:unknown)=>Buffer.from('{"alg":"HS256","typ":"JWT"}').toString('base64url')+'.'+Buffer.from(JSON.stringify(payload)).toString('base64url')+'.stub-signature',jwt=(session:unknown=sessionId,iat=1)=>claims({sub:owner.id,session_id:session,iat}),initialToken=jwt(),refreshedToken=jwt(sessionId,2),otherSessionToken=jwt('86909483-4a27-42b1-bd7d-72d371c97461');
 let tail=Promise.resolve();const query=async(sql:string,args:unknown[]=[])=>{if(sql.startsWith('SELECT pg_advisory_xact_lock'))return {rows:[],rowCount:1};const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows??r.rows.length};};
 const req=(path:string,payload?:unknown,cookie='nh_access='+initialToken,requestOrigin=origin)=>new NextRequest(origin+path,{method:payload===undefined?'GET':'POST',headers:{Origin:requestOrigin,Cookie:cookie,'Content-Type':'application/json'},...(payload===undefined?{}:{body:JSON.stringify(payload)})});
 const call=async(path:string,payload?:unknown,status=200,requestOrigin=origin)=>{const r=await (payload===undefined?dashboardGet:dashboard)(req('/api/dashboard/'+path,payload,'nh_access='+initialToken,requestOrigin),{params:Promise.resolve({route:path.split('/')})});const v=await r.json();assert.equal(r.status,status,JSON.stringify(v));assert(!JSON.stringify(v).includes('private-'),'dashboard response must exclude credentials');return v;};
 try{
  await db.exec((await readFile('db/dashboard.sql','utf8')).split('ALTER TABLE')[0]);g.nhPool={query,async connect(){const before=tail;let release!:()=>void;tail=new Promise<void>(r=>release=r);await before;return {query,release};}};
  Object.assign(process.env,{DATABASE_URL:'postgres://memory-only',MARKET_ORIGIN:origin,SESSION_SECRET:'test-only-adsense-security-32-characters',SUPABASE_URL:'https://auth.example.invalid',SUPABASE_PUBLISHABLE_KEY:'stub-only',OPERATOR_EMAIL:owner.email,OPERATOR_USER_ID:owner.id});
  globalThis.fetch=async(input,init)=>{
   const u=new URL(String(input));if(u.href==='https://auth.example.invalid/auth/v1/user')return Response.json(current);apiCalls++;assert(['oauth2.googleapis.com','adsense.googleapis.com'].includes(u.hostname),'only fixed Google hosts are allowed');assert.equal(init?.redirect,'error');
   if(u.hostname==='oauth2.googleapis.com'){
    const v=new URLSearchParams(String(init?.body));assert.equal(v.get('client_secret'),'private-client-secret');if(v.get('grant_type')==='refresh_token'){refreshCalls++;assert.equal(v.get('refresh_token'),'private-refresh-token');}else{assert.equal(v.get('redirect_uri'),origin+'/api/adsense');assert.match(v.get('code_verifier')!,/^[\w-]{43}$/);}
    return tokenFail?Response.json({error:'private-error-detail'},{status:400}):Response.json({access_token:'private-access-token',refresh_token:'private-refresh-token',expires_in:3600,token_type:'Bearer',scope});
   }
   assert.equal(new Headers(init?.headers).get('authorization'),'Bearer private-access-token');
   if(u.pathname==='/v2/accounts')return Response.json({accounts:[{name:other,displayName:'다른 계정',timeZone:{id:'America/Los_Angeles'}},{name:account,displayName:'블로그 계정 <확인>',timeZone:{id:'Asia/Seoul'}}]});
   if(u.pathname.endsWith('/payments')){assert.equal(u.pathname,'/v2/'+account+'/payments');return paymentsFail?Response.json({error:'private-payments-error'},{status:403}):Response.json({payments:[{name:account+'/payments/unpaid',amount:'$0.00'},{name:account+'/payments/2024-03-21',date:{year:2024,month:3,day:21},amount:'$45.67'}]});}
   assert.equal(u.pathname,'/v2/'+account+'/reports:generate');assert.equal(u.searchParams.get('filters'),'DOMAIN_CODE==doto1.tistory.com');assert.equal(u.searchParams.get('currencyCode'),'KRW');assert.equal(u.searchParams.get('reportingTimeZone'),'ACCOUNT_TIME_ZONE');assert(!u.searchParams.getAll('metrics').includes('PAGE_VIEWS_RPM'));
   if(reportMode==='error')return Response.json({error:'private-report-error'},{status:500});if(reportMode==='empty')return Response.json({totalMatchedRows:'0'});
   const date=(key:string)=>({year:Number(u.searchParams.get(key+'.year')),month:Number(u.searchParams.get(key+'.month')),day:Number(u.searchParams.get(key+'.day'))}),values=reportMode==='zero'?['0','0','0','0']:['123.45','1000','2000','30'];
   return Response.json({totalMatchedRows:'1',headers:[{name:'DOMAIN_CODE',type:'DIMENSION'},{name:'ESTIMATED_EARNINGS',type:'METRIC_CURRENCY',currencyCode:'KRW'},...['PAGE_VIEWS','IMPRESSIONS','CLICKS'].map(name=>({name,type:'METRIC_TALLY'}))],rows:[{cells:[{value:'doto1.tistory.com'},...values.map(value=>({value:reportMode==='partial'&&value==='2000'?'':value}))]}],startDate:date('startDate'),endDate:date('endDate')});
  };
  const appInput={version:1,clientId:'test-client.apps.googleusercontent.com',clientSecret:'private-client-secret'};
  await call('adsense/app',appInput,403,'https://evil.example');current=viewer;await call('adsense/app',appInput,403);assert.equal((await connect(req('/api/adsense',{version:1}))).status,403);current=owner;
  await call('adsense/app',appInput);await call('adsense/app',appInput,409);let ctx=await context('live');assert(!JSON.stringify(ctx.get('adsense-app','config')).includes('private-client-secret'));
  const unchanged=ctx.get('adsense-app','config').secret;await call('adsense/app',{version:2,clientId:'changed.apps.googleusercontent.com'},400);await call('adsense/app',{version:2,clientId:appInput.clientId});ctx=await context('live');assert.equal(ctx.get('adsense-app','config').secret,unchanged,'blank secret preserves credentials');
  assert.equal((await connect(req('/api/adsense',{version:2},'nh_access='+initialToken,'https://evil.example'))).status,403);
  assert.equal((await connect(req('/api/adsense',{version:1}))).status,409);
  const invalidTokens=['owner-session',claims({sub:owner.id}),jwt('not-a-uuid'),jwt(123)];for(const token of invalidTokens)assert.equal((await connect(req('/api/adsense',{version:3},'nh_access='+token))).status,403,'missing or malformed stable session identity must fail closed');
  const start=await connect(req('/api/adsense',{version:3}));assert.equal(start.status,200);const auth=new URL((await start.json()).url),cookie=start.cookies.get('nh_adsense')!.value,browser=JSON.parse(unseal(cookie));assert.equal(auth.searchParams.get('scope'),scope);assert.equal(auth.searchParams.get('include_granted_scopes'),'false');assert.equal(auth.searchParams.get('code_challenge_method'),'S256');assert.equal(auth.searchParams.get('redirect_uri'),origin+'/api/adsense');assert.match(start.headers.get('set-cookie')!,/HttpOnly/);assert.match(start.headers.get('set-cookie')!,/Secure/);
  const callbackReq=(state=browser.state,flowCookie=cookie,session=initialToken)=>req('/api/adsense?code=test-code&state='+state,undefined,'nh_access='+session+'; nh_adsense='+flowCookie);
  const before=apiCalls;for(const bad of [callbackReq('wrong'),callbackReq(browser.state,cookie,otherSessionToken),callbackReq(browser.state,seal(JSON.stringify({...browser,expires:Date.now()-1}))),...invalidTokens.map(token=>callbackReq(browser.state,cookie,token))])assert.match((await callback(bad)).headers.get('location')!,/adsense=failed/);assert.equal(apiCalls,before);
  current=viewer;assert.match((await callback(callbackReq())).headers.get('location')!,/adsense=failed/);current=owner;
  assert.notEqual(initialToken,refreshedToken);const done=await callback(callbackReq(browser.state,cookie,refreshedToken));assert.match(done.headers.get('location')!,/adsense=connected/,'refreshing the access JWT must preserve an owner session’s pending consent');assert.equal(done.cookies.get('nh_adsense')!.value,'');assert(!JSON.stringify([...done.headers]).includes('private-'));const after=apiCalls;assert.match((await callback(callbackReq(browser.state,cookie,refreshedToken))).headers.get('location')!,/adsense=failed/);assert.equal(apiCalls,after,'replay must not reach Google');
  ctx=await context('live');const connected=ctx.get('adsense-connection','google');assert.equal(connected.selectedAccount,null,'even multiple accessible accounts must never auto-select');assert.equal(ctx.decrypt(connected.secret).refreshToken,'private-refresh-token');assert(!JSON.stringify(connected).includes('private-access-token'));
  await call('adsense/report',{month:'2024-02'},400);await call('adsense/account',{version:1,account:'accounts/pub-999'},400);await call('adsense/account',{version:1,account});await call('adsense/account',{version:1,account},409);
  ctx=await context('live');await ctx.put('analytics','2024-02',{month:'2024-02',ga:{revenue:999},marker:'GA4 preserved'});const ledgerBefore=(await query('SELECT * FROM nh_money ORDER BY workspace,id')).rows;
  let state=await call('adsense/report',{month:'2024-02'}),report=state.adsense.reports.find((r:any)=>r.month==='2024-02');assert.equal(report.metrics.estimatedEarnings,123.45);assert.equal(report.metrics.pageRPM,123.45);assert.equal(report.currencyCode,'KRW');assert.equal(report.timeZone,'Asia/Seoul');assert.equal(report.endDate,'2024-02-29');assert.equal(state.adsense.payments[0].items[1].amount,'$45.67');assert.equal(state.google.reports[0].marker,'GA4 preserved');
  const success=report;reportMode='error';paymentsFail=true;state=await call('adsense/report',{month:'2024-02'});report=state.adsense.reports.find((r:any)=>r.month==='2024-02');assert.deepEqual(report.metrics,success.metrics);assert.equal(report.observedAt,success.observedAt);assert.equal(report.stale,true);assert(report.error);assert.equal(state.adsense.payments[0].stale,true);assert.equal(state.adsense.payments[0].items[1].amount,'$45.67');
  reportMode='empty';state=await call('adsense/report',{month:'2024-01'});assert.equal(state.adsense.reports.find((r:any)=>r.month==='2024-01').metrics,null,'no data is unknown');
  reportMode='partial';state=await call('adsense/report',{month:'2024-02'});assert.deepEqual(state.adsense.reports.find((r:any)=>r.month==='2024-02').metrics,success.metrics,'invalid/missing metric preserves previous complete report');
  reportMode='zero';paymentsFail=false;state=await call('adsense/report',{month:'2024-02'});report=state.adsense.reports.find((r:any)=>r.month==='2024-02');assert.equal(report.metrics.estimatedEarnings,0);assert.equal(report.metrics.pageViews,0);assert.equal(report.metrics.pageRPM,null);assert.equal(report.stale,false);
  ctx=await context('live');const expired=ctx.get('adsense-connection','google');await ctx.put('adsense-connection','google',{...expired,secret:ctx.encrypt({...ctx.decrypt(expired.secret),expiresAt:new Date(0).toISOString()})});await call('adsense/report',{month:'2024-02'});assert.equal(refreshCalls,1,'expired tokens refresh with encrypted client credentials');
  ctx=await context('live');const expiredAgain=ctx.get('adsense-connection','google');await ctx.put('adsense-connection','google',{...expiredAgain,secret:ctx.encrypt({...ctx.decrypt(expiredAgain.secret),expiresAt:new Date(0).toISOString()})});tokenFail=true;state=await call('adsense/report',{month:'2024-02'});assert.equal(state.adsense.reports.find((r:any)=>r.month==='2024-02').metrics.estimatedEarnings,0);assert.equal(state.adsense.reports.find((r:any)=>r.month==='2024-02').stale,true);
  assert.deepEqual((await query('SELECT * FROM nh_money ORDER BY workspace,id')).rows,ledgerBefore,'estimated earnings and payments never create ledger entries');assert.equal((await context('live')).get('analytics','2024-02').marker,'GA4 preserved');
  await query("INSERT INTO nh_documents(workspace,kind,id,data) VALUES('live','access',$1,$2)",[viewer.id,JSON.stringify({email:viewer.email,status:'approved'})]);current=viewer;await call('adsense/report',{month:'2024-02'},403);await call('adsense/account',{version:2,account},403);const viewerState=await call('state');assert(!JSON.stringify(viewerState).includes('private-'));current=owner;
  const source=await readFile('public/one/app.js','utf8'),panel=source.slice(source.indexOf('function adsensePanel(){'),source.indexOf('\nfunction ',source.indexOf('function adsensePanel(){')+10));
  const ui:any={data:state,session:{readOnly:false},state:{month:'2024-02'},location:{origin},esc:(v:unknown)=>String(v??'').replace(/</g,'&lt;'),dt:(v:unknown)=>v||'미확인',money:(v:unknown)=>String(v),button:()=>'',disclosure:(_l:string,s:string)=>s,formField:()=>'',selectField:(_l:string,_n:string,rows:unknown)=>JSON.stringify(rows),notice:(s:string)=>s,table:(_h:unknown,rows:unknown)=>JSON.stringify(rows),row:(v:unknown)=>v,empty:(s:string)=>s};vm.createContext(ui);vm.runInContext(panel,ui);let html=vm.runInContext('adsensePanel()',ui);assert(html.includes('확정 수익 아님')&&html.includes('이전 조회값')&&html.includes('계정 전체')&&html.includes('$45.67'));assert(html.includes('Google 지급통화 원문'));assert(html.includes(account)&&html.includes(other));ui.session.readOnly=true;html=vm.runInContext('adsensePanel()',ui);assert(!html.includes('adsense-app-form')&&!html.includes('adsense-account-form'));ui.data.adsense.selectedAccount=null;html=vm.runInContext('adsensePanel()',ui);assert(html.includes('미확인')&&!html.includes('$45.67'));
  assert.throws(()=>parsePayments({payments:[{name:other+'/payments/unpaid',amount:'$0.00'}]},account));assert.throws(()=>parseReport({rows:[]},{startDate:'2024-02-01',endDate:'2024-02-29'}));
 }finally{globalThis.fetch=priorFetch;g.nhPool=priorPool;await db.close();for(const key of Object.keys(process.env))if(!(key in priorEnv))delete process.env[key];Object.assign(process.env,priorEnv);}
});
