'use strict';
const assert=require('node:assert/strict');
const {validateSEO,renderMarkdown,preview,repurpose,weight}=require('../src/server/content-tools.cjs');
const {controller,preflight,inspectPublication,defaultPublishingSettings,validatePublishingSettings}=require('../src/server/dashboard.cjs');
async function manualRegistrations(){
 const {PGlite}=require('@electric-sql/pglite'),fs=require('node:fs'),dns=require('node:dns').promises,db=new PGlite();
 const previous={pool:globalThis.nhPool,fetch:globalThis.fetch,lookup:dns.lookup,database:process.env.DATABASE_URL,secret:process.env.SESSION_SECRET};let failAudit=false,tail=Promise.resolve(),locks=0;const lockKeys=[];
 const query=async(sql,args=[])=>{if(sql.startsWith('SELECT pg_advisory_xact_lock')){locks++;lockKeys.push(args[0]);return {rows:[],rowCount:1};}if(failAudit&&sql.startsWith('INSERT INTO nh_audit')){failAudit=false;throw Error('test audit rollback');}const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows??r.rows.length};};
 try{
  await db.exec(fs.readFileSync('db/dashboard.sql','utf8').split('ALTER TABLE')[0]);
  // PGlite has one session and no advisory locks; serialize its transaction connections.
  globalThis.nhPool={query,async connect(){const prior=tail;let release;tail=new Promise(r=>release=r);await prior;return {query,release};}};
  process.env.DATABASE_URL='postgres://memory-test-only';process.env.SESSION_SECRET='test-only-manual-registration-secret-32-characters';
  dns.lookup=async hostname=>{assert.equal(hostname,'doto1.tistory.com');return [{address:'203.0.113.1',family:4}];};globalThis.fetch=async()=>assert.fail('recording manual URLs or daily growth must not call an external API');
  const seed=async(id,channel,extra={})=>query("INSERT INTO nh_documents(workspace,kind,id,data) VALUES('live','content',$1,$2)",[id,JSON.stringify({service:'tistory',business:'platform',channel,...(channel==='blog'?{blogTarget:'tistory'}:{}),title:'회귀 검사 초안',body:'본문',status:'review',version:3,uncertain:true,error:'확인 필요',scheduledAt:'2026-10-08T00:00:00Z',...extra})]);
  const call=async(c,route,value,status=200)=>{const r=await c.handle({method:'POST'},route,value,'test@example.invalid'),body=await r.json();assert.equal(r.status,status,JSON.stringify(body.error));return body;};
  const row=async id=>(await query("SELECT data FROM nh_documents WHERE workspace='live' AND kind='content' AND id=$1",[id])).rows[0].data;
  const auditCount=async()=>Number((await query('SELECT count(*) n FROM nh_audit')).rows[0].n);
  for(const [channel,url,other] of [['blog','https://doto1.tistory.com/170','https://doto1.tistory.com/171'],['youtube','https://www.youtube.com/watch?v=sample-only','https://www.youtube.com/watch?v=other'],['tiktok','https://www.tiktok.com/@sample/video/123','https://www.tiktok.com/@sample/video/456'],['instagram','https://www.instagram.com/p/Cabc123xyz/','https://www.instagram.com/p/Cdef456uvw/'],['threads','https://www.threads.com/@sample/post/DAbc12345','https://www.threads.com/@sample/post/DDef67890'],['x','https://x.com/sample/status/1840000000000000001','https://x.com/sample/status/1840000000000000002']]){
   const id=channel+'-a',duplicate=channel+'-b',route=channel==='blog'?'/api/content/manual':'/api/studio/manual';await seed(id,channel);await seed(duplicate,channel);const c=await controller({demo:false});
   await call(c,route,{id,url},400);await call(c,route,{id,url,version:2},409);assert.equal((await row(id)).version,3);
   if(channel==='blog')for(const invalid of ['https://doto1.tistory.com.evil.test/170','https://user:secret@doto1.tistory.com/170','https://doto1.tistory.com:443/170','https://doto1.tistory.com/category/tools','https://doto1.tistory.com/manage/posts','https://doto1.tistory.com/entry/a%2Fb','http://doto1.tistory.com/170'])await call(c,route,{id,url:invalid,version:3},400);
   await call(c,route,{id,url:channel==='blog'?url+'/?utm_source=test#section':url,version:3});const saved=await row(id),count=await auditCount();
   assert.equal(saved.link,url);assert.equal(saved.version,4);assert.equal(saved.status,'published');assert.equal(saved.manual,true);assert.equal(saved.checkStatus,'registered');assert.equal(saved.checkedAt,null);assert.equal(saved.uncertain,false);assert.equal(saved.error,null);assert.equal(saved.scheduledAt,null);assert(saved.registeredAt&&saved.updatedAt&&saved.publishedAt);
   await call(c,route,{id,url,version:3});assert.deepEqual(await row(id),saved);assert.equal(await auditCount(),count,'retry must not write or audit');
   await call(c,route,{id,url:other,version:4},409);await call(c,route,{id:duplicate,url:channel==='blog'?url+'?utm_campaign=duplicate#x':url,version:3},409);assert.equal((await row(duplicate)).status,'review');assert.equal(await auditCount(),count);
   await call(c,'/api/content/publish',{id},400);await call(c,'/api/content/schedule',{id},400);assert.deepEqual(await row(id),saved,'registered content must never reenter publication');
   assert.equal((await call(c,'/api/content/check',{id})).contents.find(p=>p.id===id).checkStatus,channel==='blog'?'unavailable':'registered');
  }
  {
   const reg=async(id,channel,url,status=200,version=3,extra={})=>{await seed(id,channel,extra);return call(await controller({demo:false}),'/api/studio/manual',{id,url,version},status);};
   await reg('sv-ig','instagram','https://instagram.com/sample.user/p/Cvar123xyz?igsh=abc#x',200,3,{account:'api-account',container:'17900000000000001'});assert.equal((await row('sv-ig')).link,'https://www.instagram.com/p/Cvar123xyz/');assert.equal((await row('sv-ig')).account,null);assert.equal((await row('sv-ig')).container,null);
   await reg('sv-reel','instagram','https://www.instagram.com/reels/Creel12345/');assert.equal((await row('sv-reel')).link,'https://www.instagram.com/reel/Creel12345/');
   await reg('sv-x','x','https://twitter.com/sample/status/1840000000000000009?s=20');assert.equal((await row('sv-x')).link,'https://x.com/sample/status/1840000000000000009');
   await reg('sv-x-web','x','https://mobile.twitter.com/i/web/status/1840000000000000044?s=20');assert.equal((await row('sv-x-web')).link,'https://x.com/i/web/status/1840000000000000044');await reg('sv-x-web-dup','x','https://x.com/sample/status/1840000000000000044',409);await reg('sv-x-dup','x','https://mobile.twitter.com/i/web/status/1840000000000000009',409);
   await reg('sv-x-same','x','https://x.com/other/status/1840000000000000009/',409);assert.equal((await row('sv-x-dup')).status,'review');assert.equal((await row('sv-x-same')).status,'review');
   await seed('api-x','x',{status:'published',externalId:'1840000000000000077',link:'https://x.com/i/status/1840000000000000077'});await seed('api-x2','x',{status:'published',externalId:'1840000000000000066',link:null});await reg('sv-x-api','x','https://x.com/sample/status/1840000000000000077',409);
   await reg('sv-x-api2','x','https://x.com/sample/status/1840000000000000066',409);
   const bad=[['instagram','https://www.threads.com/@sample/post/DAbc12345'],['instagram','https://instagram.com.evil.example/p/Cabc123xyz/'],['instagram','https://www.instagram.com/accounts/login/?next=/p/Cabc123xyz/'],['instagram','https://www.instagram.com/sample/'],['threads','https://www.threads.com/@sample'],['threads','http://www.threads.com/@sample/post/DAbc12345'],['threads','https://www.threads.com:443/@sample/post/DAbc12345'],['threads','https://user:secret@www.threads.com/@sample/post/DAbc12345'],['x','https://x.com/sample/status/123/photo/1'],['x','https://x.com/intent/post?text=a'],['x','https://127.0.0.1/p/x'],['x','https://www.instagram.com/p/Cabc123xyz/'],['x','https://x.com/sample/status/01840000000000000009'],['instagram','https://www.instagram.com/stories/p/12345678/'],['instagram','https://www.instagram.com/explore/p/Cabc123xyz/']];
   for(const [channel,url] of bad){const id='bad-'+channel;await seed(id,channel);await call(await controller({demo:false}),'/api/studio/manual',{id,url,version:3},400);assert.equal((await row(id)).status,'review');await query("DELETE FROM nh_documents WHERE id=$1",[id]);}
   await seed('sv-stale','threads');await call(await controller({demo:false}),'/api/studio/manual',{id:'sv-stale',url:'https://www.threads.net/@sample/post/DStale123',version:2},409);assert.equal((await row('sv-stale')).status,'review');
   for(const status of ['scheduled','publishing','published'])await reg('sv-'+status,'instagram','https://www.instagram.com/p/C'+status+'1/',409,3,{status,uncertain:false});
   await reg('sv-draft','threads','https://www.threads.com/@sample/post/DDraft123',200,3,{status:'draft'});await reg('sv-approved','x','https://x.com/sample/status/1840000000000000123',200,3,{status:'approved',uncertain:false});
   await seed('sv-race-a','instagram');await seed('sv-race-b','instagram');lockKeys.length=0;const ra=await controller({demo:false}),rb=await controller({demo:false}),race2=await Promise.all([ra.handle({method:'POST'},'/api/studio/manual',{id:'sv-race-a',url:'https://www.instagram.com/p/Crace12345/',version:3},'test@example.invalid'),rb.handle({method:'POST'},'/api/studio/manual',{id:'sv-race-b',url:'https://instagram.com/sample/reel/Crace12345?igsh=z',version:3},'test@example.invalid')]);assert.deepEqual(race2.map(r=>r.status).sort(),[200,409]);assert.deepEqual(lockKeys.filter(k=>k.includes('content.manual')),['live:content.manual:instagram:Crace12345','live:content.manual:instagram:Crace12345'],'same post in different URL forms must share one lock');
   for(const channel of ['instagram','threads','x'])preflight({service:'tistory',channel,body:'본문',media:'https://example.com/image.jpg'});
   assert.equal((await call(await controller({demo:false}),'/api/content/check',{id:'sv-ig'})).contents.find(p=>p.id==='sv-ig').checkStatus,'registered');assert.equal((await row('sv-ig')).checkedAt,null);
   const ch=await controller({demo:true});try{await ch.handle({method:'POST'},'/api/channel',{service:'tistory',channel:'threads',label:'스레드 테스트',token:'sample'},'test@example.invalid').then(async r=>{const b=await r.json();assert(!/API 계정 연결을 지원하지 않습니다/.test(b.error||''),b.error);});}catch(e){assert(!/API 계정 연결을 지원하지 않습니다/.test(e.message),e.message);}
  }
  for(const channel of ['threads','instagram','x']){
   const id='manual-'+channel;await seed(id,channel,{status:'published',manual:true,externalId:'manual:https://example.invalid/post',link:'https://example.invalid/post',checkStatus:'registered',checkedAt:null});const c=await controller({demo:false,inspect:()=>assert.fail('manual SNS links have no provider API ID')});
   await call(c,'/api/content/check',{id});const saved=await row(id);assert.equal(saved.status,'published');assert.equal(saved.checkStatus,'registered');assert.equal(saved.checkedAt,null);assert.equal(saved.externalId,'manual:https://example.invalid/post');assert.equal((await query('SELECT action FROM nh_audit WHERE target=$1 ORDER BY id DESC LIMIT 1',[id])).rows[0].action,'content.url_registration_checked');
  }
  await seed('stale-context','youtube');const stale=await controller({demo:false});await query("UPDATE nh_documents SET data=jsonb_set(data,'{version}','4') WHERE id='stale-context'");await call(stale,'/api/studio/manual',{id:'stale-context',url:'https://youtu.be/stale',version:3},409);assert.equal((await row('stale-context')).version,4);
  await seed('rollback','youtube');const rollback=await controller({demo:false}),before=await row('rollback'),count=await auditCount();failAudit=true;await call(rollback,'/api/studio/manual',{id:'rollback',url:'https://youtu.be/rollback',version:3},500);assert.deepEqual(await row('rollback'),before);assert.equal(await auditCount(),count);
  await seed('race-a','youtube');await seed('race-b','youtube');const a=await controller({demo:false}),b=await controller({demo:false}),race=await Promise.all([a.handle({method:'POST'},'/api/studio/manual',{id:'race-a',url:'https://youtu.be/same-post',version:3},'test@example.invalid'),b.handle({method:'POST'},'/api/studio/manual',{id:'race-b',url:'https://youtu.be/same-post',version:3},'test@example.invalid')]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);assert(locks>0,'registration must acquire the workspace URL lock');
  const growth=await controller({demo:false}),moneyBefore=(await query('SELECT * FROM nh_money ORDER BY workspace,id')).rows,dailyFields=['views','reach','profileVisits','follows','unfollows','likes','replies','shares','saves'],financeFields=['impressions','clicks','leads','orders','revenue','cost'],resultFields=[...dailyFields,...financeFields];
  const campaignState=await call(growth,'/api/growth/campaign',{service:'tistory',name:'계정 성장',model:'audience'}),campaign=campaignState.growthCampaigns.find(c=>c.name==='계정 성장');assert.equal(campaign.model,'audience');assert.equal(campaign.url,'');
  for(const model of ['product','affiliate','lead','sponsor','ads'])await call(growth,'/api/growth/campaign',{service:'tistory',name:'기존 '+model,model,url:'https://public.example.invalid/offer'});
  const input={campaignId:campaign.id,day:'2026-10-08',channel:'x',impressions:100,clicks:10,leads:2,orders:1,revenue:1000,cost:100,note:'채널의 당일 증가분 확인'};
  const unknownState=await call(growth,'/api/growth/result',{...input,views:null,impressions:undefined,clicks:null,leads:undefined,orders:null,revenue:null,cost:undefined}),unknown=unknownState.growthResults.find(r=>r.note===input.note);for(const field of resultFields)assert.equal(unknown[field],null,'missing/null must stay unknown');
  const reloadedUnknown=(await controller({demo:false})).view().growthResults.find(r=>r.id===unknown.id);for(const field of financeFields)assert.equal(reloadedUnknown[field],null,'unknown finance values must reload as null');
  const zeros=Object.fromEntries(resultFields.map(field=>[field,0])),zeroState=await call(growth,'/api/growth/result',{...input,day:'2026-10-09',note:'확인한 0',...zeros}),zero=zeroState.growthResults.find(r=>r.note==='확인한 0');for(const field of resultFields)assert.equal(zero[field],0,'an observed zero must not become unknown');
  const counts=Object.fromEntries(dailyFields.map((field,index)=>[field,index+1])),updatedState=await call(growth,'/api/growth/result',{...input,id:unknown.id,version:unknown.version,...counts}),updated=updatedState.growthResults.find(r=>r.id===unknown.id);assert.equal(updated.version,2);assert.equal(updated.revenue,input.revenue);assert.equal(updated.cost,input.cost);
  await call(growth,'/api/growth/result',{...input,...zeros},409);await call(growth,'/api/growth/result',{...input,id:zero.id,version:zero.version,...zeros},409);
  await call(growth,'/api/growth/result',{...input,id:unknown.id,version:unknown.version,...zeros},409);
  for(const field of resultFields)for(const invalid of [-1,0.5,'0','',true,1e10+1])await call(growth,'/api/growth/result',{...input,id:unknown.id,version:updated.version,...counts,[field]:invalid},400);
  const maximum=await call(growth,'/api/growth/result',{...input,day:'2026-10-10',...Object.fromEntries(resultFields.map(field=>[field,1e10]))});for(const field of resultFields)assert.equal(maximum.growthResults.find(r=>r.day==='2026-10-10')[field],1e10);
  const salesCampaign=maximum.growthCampaigns.find(c=>c.model==='affiliate');for(let i=0;i<2;i++)await call(growth,'/api/growth/result',{...input,campaignId:salesCampaign.id,note:'기존 판매 기록 '+i});
  const growthA=await controller({demo:false}),growthB=await controller({demo:false}),dailyRace=await Promise.all([growthA.handle({method:'POST'},'/api/growth/result',{...input,day:'2026-10-11'},'test@example.invalid'),growthB.handle({method:'POST'},'/api/growth/result',{...input,day:'2026-10-11'},'test@example.invalid')]);assert.deepEqual(dailyRace.map(r=>r.status).sort(),[200,409]);
  const partialState=await call(growth,'/api/growth/result',{...input,day:'2026-10-12',revenue:1000,cost:null,clicks:null}),partial=partialState.growthResults.find(r=>r.day==='2026-10-12');assert.equal(partial.revenue,1000);assert.equal(partial.cost,null);assert.equal(partial.clicks,null);
  const fresh=(await controller({demo:false})).view(),reloaded=fresh.growthResults.find(r=>r.id===unknown.id);for(const field of dailyFields)assert.equal(reloaded[field],counts[field]);assert.deepEqual(reloaded,updated);assert(fresh.growthResults.find(r=>r.id===zero.id));assert.equal(fresh.growthCampaigns.find(c=>c.id===campaign.id).url,'');assert.deepEqual((await query('SELECT * FROM nh_money ORDER BY workspace,id')).rows,moneyBefore,'growth counters must not create live or sample financial transactions');
  for(const field of financeFields)assert.equal(fresh.growthResults.find(r=>r.id===zero.id)[field],0);assert.deepEqual(fresh.growthResults.find(r=>r.id===partial.id),partial);
  await query("INSERT INTO nh_documents(workspace,kind,id,data) VALUES('live','analytics','2026-09',$1)",[JSON.stringify({month:'2026-09',ga:{views:999,revenue:999}})]);
  assert.equal((await controller({demo:false})).view().google.reports.find(r=>r.month==='2026-09').ga,null,'legacy property-wide GA4 totals must not be shown as Tistory');
  const {privateKey}=require('node:crypto').generateKeyPairSync('rsa',{modulusLength:2048});
  await call(await controller({demo:false}),'/api/google',{propertyId:'123456789',siteUrl:'https://doto1.tistory.com/',credentials:JSON.stringify({type:'service_account',client_email:'reader@example.invalid',private_key:privateKey.export({type:'pkcs8',format:'pem'})})});
  let gaReply={rows:[{metricValues:['0','2','3','4.5'].map(value=>({value}))}]},searchReply={rows:[{clicks:0,impressions:2,ctr:0,position:5}]};
  globalThis.fetch=async(url,init)=>{const u=new URL(url);assert.equal(init.redirect,'error');if(u.hostname==='oauth2.googleapis.com')return Response.json({access_token:'test-google-token'});const body=JSON.parse(init.body);if(u.hostname==='analyticsdata.googleapis.com'){assert.deepEqual(body.dimensionFilter,{filter:{fieldName:'hostName',stringFilter:{matchType:'EXACT',value:'doto1.tistory.com',caseSensitive:false}}},'exclude other streams in the same property');return Response.json(gaReply);}assert.equal(u.hostname,'www.googleapis.com');assert.match(u.pathname,/sites\/https%3A%2F%2Fdoto1\.tistory\.com%2F\/searchAnalytics\/query$/);return Response.json(body.dimensions.length?{rows:[]}:searchReply);};
  let report=(await call(await controller({demo:false}),'/api/google/report',{month:'2026-10'})).google.reports.find(r=>r.month==='2026-10');
  assert.deepEqual(report.ga,{users:0,sessions:2,views:3,revenue:4.5});assert.equal(report.gaHostName,'doto1.tistory.com');assert.equal(report.search.clicks,0);
  gaReply={rows:[]};searchReply={};report=(await call(await controller({demo:false}),'/api/google/report',{month:'2026-10'})).google.reports.find(r=>r.month==='2026-10');assert.equal(report.ga??null,null);assert.match(report.gaError,/집계 데이터/);assert.equal(report.search,null);assert.match(report.searchError,/집계 데이터/);
  for(const missing of [undefined,'','not-a-number','Infinity']){gaReply={rows:[{metricValues:[{value:'1'},{value:'2'},{value:'3'},{value:missing}]}]};report=(await call(await controller({demo:false}),'/api/google/report',{month:'2026-10'})).google.reports.find(r=>r.month==='2026-10');assert.equal(report.ga??null,null);assert.match(report.gaError,/응답/);}
  for(const count of ['-1','1.5','9007199254740992']){gaReply={rows:[{metricValues:[{value:count},{value:'2'},{value:'3'},{value:'4.5'}]}]};report=(await call(await controller({demo:false}),'/api/google/report',{month:'2026-10'})).google.reports.find(r=>r.month==='2026-10');assert.equal(report.ga??null,null);assert.match(report.gaError,/응답/);}
  assert.deepEqual((await query('SELECT * FROM nh_money ORDER BY workspace,id')).rows,moneyBefore,'Google metrics never create financial ledger entries');
 }finally{globalThis.nhPool=previous.pool;globalThis.fetch=previous.fetch;dns.lookup=previous.lookup;for(const [key,value] of [['DATABASE_URL',previous.database],['SESSION_SECRET',previous.secret]])if(value===undefined)delete process.env[key];else process.env[key]=value;await db.close();}
}
async function run(){
 const publishing=defaultPublishingSettings();assert.deepEqual(publishing,{timezone:'Asia/Seoul',dailyCount:5,times:['08:00','12:00','16:00','20:00','22:00'],enabled:false,version:1});
 assert.equal(validatePublishingSettings({timezone:'Asia/Seoul',dailyCount:1,times:['08:30'],enabled:false},null).version,2);
 const saved=validatePublishingSettings({timezone:'Asia/Seoul',dailyCount:2,times:['09:30','18:00'],enabled:false},{version:4});assert.deepEqual({timezone:saved.timezone,dailyCount:saved.dailyCount,times:saved.times,enabled:saved.enabled,version:saved.version},{timezone:'Asia/Seoul',dailyCount:2,times:['09:30','18:00'],enabled:false,version:5});
 for(const invalid of [{dailyCount:0,times:[],timezone:'Asia/Seoul',enabled:false},{dailyCount:2,times:['09:00'],timezone:'Asia/Seoul',enabled:false},{dailyCount:2,times:['09:00','09:00'],timezone:'Asia/Seoul',enabled:false},{dailyCount:1,times:['24:00'],timezone:'Asia/Seoul',enabled:false},{dailyCount:1,times:['09:00'],timezone:'UTC',enabled:false},{dailyCount:1,times:['09:00'],timezone:'Asia/Seoul',enabled:true},{dailyCount:1,times:['09:00'],timezone:'Asia/Seoul',enabled:'false'}])assert.throws(()=>validatePublishingSettings(invalid,null));
 const input={title:'공개 자료로 안내하는 누리 서비스',body:'누리 서비스의 이용 방법을 공개 자료에 따라 명확하고 간결하게 설명합니다.\n\n## 이용 방법\n**안내**를 확인하세요. [공식 자료](https://example.com/guide)\n\n<script>alert(1)</script>\n[위험](javascript:alert(1))\n[상대](/secret)',seo:{title:'누리 서비스 이용 방법',description:'누리 서비스의 이용 방법과 확인할 내용을 공개 자료를 바탕으로 설명합니다.',slug:'누리-서비스',keyword:'누리',cta:'공식 안내를 확인하세요.',url:'https://example.com/article',sources:[{title:'공식 안내',url:'https://example.com/guide'}],affiliate:false}};
 const result=preview(input);assert.match(result.html,/<h2>이용 방법<\/h2>/);assert.match(result.html,/<strong>안내<\/strong>/);assert.match(result.html,/&lt;script&gt;/);assert.doesNotMatch(result.html,/<script|href="javascript:|href="\/secret"/i);assert.match(result.document,/rel="canonical"/);assert.equal(result.analysis.headings[0].text,'이용 방법');assert.equal(result.analysis.links[0].url,'https://example.com/guide');assert.equal(result.analysis.score,100);
 const article=preview({...input,body:'# 본문 소제목\n\n'+input.body+'\n\n| 항목 | 값 |\n| --- | --- |\n| 긴 값 | '+ 'x'.repeat(200)+' |\n\n```\n'+'x'.repeat(200)+'\n```\n\n<style>body{display:none}</style>'});
 assert(article.document.includes(article.html),'preview, clipboard HTML and document must share the exact safe article fragment');
 assert.equal((article.document.match(/<h1(?:\s|>)/g)||[]).length,1);assert.match(article.html,/<h2>본문 소제목<\/h2>/);assert.match(renderMarkdown('# 원본 제목'),/<h1>원본 제목<\/h1>/);
 assert.equal((article.html.match(/<style>/g)||[]).length,1);assert.match(article.html,/&lt;style&gt;body\{display:none\}&lt;\/style&gt;/);assert.doesNotMatch(article.html,/<article|<h1|<script/i);
 const articleCSS=article.html.match(/<style>([\s\S]*?)<\/style>/)[1];
 for(const rule of articleCSS.trim().split('}').filter(s=>s.trim()))for(const selector of rule.split('{')[0].split(','))assert(selector.trim().startsWith('.nuri-article.nuri-article'),'article CSS must not affect dashboard or platform chrome');
 for(const rule of ['font:400 18px/1.85','max-width:860px','max-width:100%','overflow-wrap:anywhere','overflow-x:auto','white-space:pre-wrap','height:auto','a:focus-visible','background:#fff!important','color:#164b99!important'])assert(articleCSS.includes(rule),rule);
 const hostile=preview({...input,title:'<img src=x onerror=alert(1)>',seo:{...input.seo,title:'</title><script>bad</script>',description:'" onload="bad </script><script>bad</script>'}});
 assert.doesNotMatch(hostile.document,/<img|<script>bad|<\/title><script>/i);assert.equal((hostile.document.match(/<\/script>/g)||[]).length,1);assert.match(hostile.document,/\\u003c/);
 const image=renderMarkdown('![대체 텍스트](https://example.com/x.svg "사진")');assert.match(image,/<img src="https:\/\/example\.com\/x\.svg" alt="대체 텍스트" title="사진" loading="lazy" decoding="async" style="max-width:100%;height:auto"\s\/>/);assert.match(preview({...input,body:'![대체 텍스트](https://example.com/x.svg)'}).html,/alt="대체 텍스트" loading="lazy" decoding="async" style="max-width:100%;height:auto"/);assert.match(preview({...input,body:'![대체 텍스트](https://example.com/x.svg)',seo:{...input.seo,description:''}}).document,/<meta name="description" content="대체 텍스트">/);
 for(const url of ['http://example.com/x.png','data:image/png;base64,AAAA','javascript:alert(1)','//evil.test/x.png','https://user:secret@example.com/x.png'])assert.doesNotMatch(renderMarkdown(`![safe alt](${url})`),/<img\s|\ssrc=|\sonerror=/i);
 const rawHTML=renderMarkdown('<img src="https://example.com/x.png" alt="x" onerror="alert(1)">');assert.match(rawHTML,/&lt;img/);assert.doesNotMatch(rawHTML,/<img\s/);
 assert.doesNotMatch(renderMarkdown('[bad](http://example.com) [bad2](//evil.test)'),/href=/);
 for(const seo of [{url:'javascript:alert(1)'},{url:'https://user:secret@example.com'},{sources:Array(11).fill({title:'x',url:'https://example.com'})},{sources:[{title:'x',url:'data:text/html,hi'}]},{affiliate:'true'},{slug:'../bad'}])assert.throws(()=>validateSEO(seo),{status:400});
 assert.throws(()=>preview({...input,body:'x'.repeat(20001)}),{status:400});assert.throws(()=>preview({...input,title:'x'.repeat(301)}),{status:400});
 assert.equal(preview({...input,seo:{...input.seo,affiliate:true}}).analysis.checks.find(c=>c.id==='disclosure').pass,false);
 assert.equal(preview({...input,body:'[광고] 이 글에는 제휴 수수료가 있습니다.\n'+input.body,seo:{...input.seo,affiliate:true}}).analysis.checks.find(c=>c.id==='disclosure').pass,true);
 assert.equal(preview({...input,body:'안'.repeat(301)+'\n제휴 수수료가 있습니다.',seo:{...input.seo,affiliate:true}}).analysis.checks.find(c=>c.id==='disclosure').pass,false);
 const channels=['blog','instagram','threads','x','facebook','linkedin','pinterest','youtube','tiktok'],limits={blog:20000,instagram:2200,threads:500,x:280,facebook:5000,linkedin:3000,pinterest:500,youtube:5000,tiktok:2200};
 for(const draft of repurpose({...input,body:'매우 긴 공개 서비스 안내입니다. '.repeat(500)},channels)){
  assert.match(draft.body,/규칙 기반 홍보 초안/);assert.match(draft.body,/https:\/\/example.com\/article/);assert(weight(draft.body,draft.channel)<=limits[draft.channel]);assert.equal(draft.ai,false);
  if(['blog','instagram','threads','x'].includes(draft.channel))preflight({...draft,service:'tistory',blogTarget:'wordpress',media:'https://example.com/image.jpg'});
  else {assert.throws(()=>preflight({...draft,service:'tistory'}),/자동 게시 API/);assert.deepEqual(await inspectPublication({...draft,externalId:'manual:x'},null,()=>assert.fail('manual posts must not fetch')),{checkStatus:'unavailable'});}
 }
 assert.throws(()=>preflight({service:'crm',channel:'x',body:'과거 기록'}),/독립 운영/);assert.equal(repurpose(input,['x','x']).length,1);assert.throws(()=>repurpose(input,['unknown']),{status:400});
 assert(repurpose({...input,body:'😀'.repeat(9999)},['blog'])[0].body.length<=20000);
 await manualRegistrations();
 console.log('PASS safe Markdown, SEO metadata/JSON-LD, disclosure checks, nine-channel repurposing, manual URL validation/CAS/duplicates/retries/rollback, serialized registration and daily audience growth unknown/zero/validation/reload/finance isolation');
}
run().catch(e=>{console.error(e);process.exitCode=1;});
