'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('@playwright/test');
const base=process.env.TEST_ORIGIN||'http://127.0.0.1:3120';
async function main(){
 const catalog=await fetch(base+'/api/catalog').then(r=>r.json()),product=catalog.products.find(p=>p.category==='clicker'&&p.variants.some(v=>v.stock>0));assert(product);
 const browser=await chromium.launch({headless:true}),page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});let screens=0;
 fs.mkdirSync('artifacts/market',{recursive:true});
 try{
  for(const width of [320,390,768,1024,1440,1920]){await page.setViewportSize({width,height:960});for(const route of ['/','/search?category=clicker','/product/'+product.slug,'/cart','/wishlist','/my','/policy/shipping','/nurimarket/login']){await page.goto(base+route);await page.locator(route.includes('login')?'form':'.header').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),width+' '+route+' overflow');screens++;}
   await page.goto(base+'/');await page.locator('.hero-campaign').waitFor();assert.equal(await page.locator('.market-shell').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(17, 24, 20)');
   for(const n of [1,2]){await page.getByRole('button',{name:n+'번 배너:',exact:false}).click();await page.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(a=>Number.isFinite(a.effect?.getTiming().iterations)).map(a=>a.finished.catch(()=>{})));});assert.equal(await page.locator('.hero-frame.is-active').count(),1);assert.equal(await page.locator('.hero-frame:not(.is-active)').getAttribute('inert'),'');const copy=await page.locator('.hero-frame.is-active .hero-copy').boundingBox(),controls=await page.locator('.hero-controls').boundingBox();assert(copy.y+copy.height<=controls.y+2,width+' banner overlaps controls');screens++;}
   if(width===390||width===1440){await page.getByRole('button',{name:'1번 배너:',exact:false}).click();await page.evaluate(async()=>{scrollTo(0,0);await Promise.all(document.getAnimations().filter(a=>Number.isFinite(a.effect?.getTiming().iterations)).map(a=>a.finished.catch(()=>{})));});await page.screenshot({path:'artifacts/market/home-'+width+'.png',fullPage:false});}
  }
  await page.setViewportSize({width:1440,height:960});await page.goto(base+'/');await page.locator('.collection-tabs').waitFor();for(const label of ['클릭커','의류·모자','전체','미니 피규어','클릭커'])await page.locator('.collection-tabs').getByRole('button',{name:label,exact:true}).click();await page.waitForFunction(()=>document.querySelector('.collection-tabs .active')?.textContent==='클릭커');assert((await page.locator('.product-card h3').allTextContents()).length>0);
  await page.getByRole('link',{name:product.name,exact:true}).click();await page.waitForURL('**/product/'+product.slug);await page.locator('.pdp-info').waitFor();await page.goBack();await page.locator('.hero-campaign').waitFor();
  await page.goto(base+'/search?category=clicker');await page.locator('.filter-chips .active').waitFor();assert.equal(await page.locator('.category-strip .active').textContent(),'클릭커');await page.locator('.filter-chips').getByRole('button',{name:'의류·모자',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.category-strip .active')?.textContent==='의류·모자');assert(new URL(page.url()).searchParams.get('category')==='apparel');await page.getByRole('textbox',{name:'상품 이름 검색'}).fill('없는-상품-검증');await page.getByRole('heading',{name:'조건에 맞는 상품이 없습니다.'}).waitFor();await page.getByRole('button',{name:'검색어 지우기'}).click();
  await page.goto(base+'/product/'+product.slug);await page.locator('.pdp-info').waitFor();for(const label of ['리뷰','배송·교환','상품정보'])await page.locator('.pdp-tabs').getByRole('button',{name:label,exact:true}).click();await page.locator('.pdp-content h2').waitFor();await page.locator('.desktop-buy').getByRole('button',{name:'장바구니',exact:true}).click();await page.locator('dialog[open]').waitFor();await page.getByRole('button',{name:'창 닫기',exact:true}).click();await page.locator('dialog[open]').waitFor({state:'hidden'});
  await page.goto(base+'/');await page.locator('.hero-campaign').waitFor();await page.getByRole('button',{name:'2번 배너:',exact:false}).press('Enter');assert.equal(await page.locator('.hero-frame.is-active').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
  await page.emulateMedia({reducedMotion:'reduce'});for(const route of ['/','/search','/product/'+product.slug]){await page.goto(base+route);await page.locator('.header').waitFor();assert(await page.evaluate(()=>document.getAnimations().every(a=>a.playState!=='running')),route+' reduced motion');}await page.emulateMedia({reducedMotion:'no-preference'});
  assert.deepEqual(errors,[]);const report={base,at:new Date().toISOString(),screens,consoleErrors:errors.length,checks:['dark storefront','banner inert slides and no control overlap','6 responsive widths','rapid category changes','product navigation and browser back','URL/category synchronization','search clear and empty state','detail tabs and cart dialog','keyboard immediate feedback','reduced motion']};fs.writeFileSync('artifacts/market/report.json',JSON.stringify(report,null,2));console.log(report);
 }finally{await browser.close();}
}
main().catch(e=>{console.error(e.name+': '+e.message);process.exitCode=1;});
