import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {NextRequest} from 'next/server';
import {POST as connect,GET as callback} from '../src/app/api/social/[provider]/route';
import {context} from '../src/server/context.cjs';
import {controller} from '../src/server/dashboard.cjs';
import {unseal} from '../src/lib/security';

test('SNS OAuth checks owner, origin, browser state, one-time consumption and encrypted persistence',async()=>{
 const db=new PGlite(),previousEnv={...process.env},previousFetch=globalThis.fetch,g=globalThis as typeof globalThis&{nhPool?:unknown},previousPool=g.nhPool;
 const origin='https://nuri.example.invalid',owner={id:'owner-id',email:'owner@example.invalid',email_confirmed_at:'2026-10-07'},viewer={...owner,id:'viewer-id'};let current=owner,providerCalls=0;
 const query=async(sql:string,args:unknown[]=[])=>{const result=await db.query(sql,args);return {...result,rowCount:result.affectedRows??result.rows.length};};
 const req=(path:string,payload?:unknown,cookie='nh_access=owner')=>new NextRequest(origin+path,{method:payload?'POST':'GET',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},...(payload?{body:JSON.stringify(payload)}:{})}),route={params:Promise.resolve({provider:'x'})};
 try{
  await db.exec((await readFile('db/dashboard.sql','utf8')).split('ALTER TABLE')[0]);g.nhPool={query,connect:async()=>({query,release(){}})};
  Object.assign(process.env,{DATABASE_URL:'postgres://test-only',MARKET_ORIGIN:origin,SESSION_SECRET:'test-only-social-encryption-32-characters',SUPABASE_URL:'https://auth.example.invalid',SUPABASE_PUBLISHABLE_KEY:'test-only',OPERATOR_EMAIL:owner.email,OPERATOR_USER_ID:owner.id});
  globalThis.fetch=async(input,init)=>{const url=String(input);if(url==='https://auth.example.invalid/auth/v1/user')return Response.json(current);providerCalls++;
   if(url==='https://api.x.com/2/oauth2/token'){assert(['authorization_code','refresh_token'].includes(new URLSearchParams(String(init?.body)).get('grant_type')!));return Response.json({access_token:'private-user-token',refresh_token:'private-refresh-token',expires_in:7200,scope:'tweet.read tweet.write users.read offline.access'});}
   if(url==='https://api.x.com/2/users/me')return Response.json({data:{id:'12345',username:'nuri_test'}});throw new Error('Unexpected real network request');
  };
  const app=await controller({}),saved=await app.handle(req('/api/dashboard/social-app',{}),'/api/social-app',{provider:'x',clientId:'public-app-id',clientSecret:'private-app-secret'},owner.email);assert.equal(saved.status,200);assert(!JSON.stringify(await saved.json()).includes('private-app-secret'));
  current=viewer;assert.equal((await connect(req('/api/social/x',{service:'tistory',label:'누리 X'}),route)).status,403);current=owner;
  assert.equal((await connect(new NextRequest(origin+'/api/social/x',{method:'POST',headers:{Origin:'https://evil.example',Cookie:'nh_access=owner','Content-Type':'application/json'},body:'{}'}),route)).status,403);
  assert.equal((await connect(req('/api/social/x',{service:'crm',label:'CRM 연결 금지'}),route)).status,400);
  const start=await connect(req('/api/social/x',{service:'tistory',label:'누리 X'}),route);assert.equal(start.status,200);const {url}=await start.json(),auth=new URL(url),cookie=start.cookies.get('nh_social')!.value,flow=JSON.parse(unseal(cookie));assert.equal(auth.searchParams.get('redirect_uri'),origin+'/api/social/x');assert.equal(auth.searchParams.get('state'),flow.state);assert.equal(auth.searchParams.get('code_challenge_method'),'S256');assert.match(start.headers.get('set-cookie')! ,/HttpOnly/);
  const before=providerCalls;const bad=await callback(req('/api/social/x?code=test-code&state=wrong',undefined,'nh_access=owner; nh_social='+cookie),route);assert.match(bad.headers.get('location')!,/social=failed/);assert.equal(providerCalls,before);
  const done=await callback(req('/api/social/x?code=test-code&state='+flow.state,undefined,'nh_access=owner; nh_social='+cookie),route);assert.match(done.headers.get('location')!,/social=connected/);assert.equal(done.cookies.get('nh_social')?.value,'');assert(!JSON.stringify([...done.headers]).includes('private-'));
  const ctx=await context('live'),account=ctx.list('channel')[0];assert.equal(account.username,'nuri_test');assert.equal(ctx.decrypt(account.secret).refreshToken,'private-refresh-token');assert(!JSON.stringify(account).includes('private-user-token'));
  const saveAI=async(payload:Record<string,unknown>)=>(await controller({})).handle(req('/api/dashboard/ai',{}),'/api/ai',payload,owner.email),aiInput={provider:'openai',model:'stub-only',token:'private-ai-token',enabled:false};
  const storedAI=await saveAI(aiInput);assert.equal(storedAI.status,200);const aiView=await storedAI.json();assert.equal(aiView.aiConfig.configured,true);assert.equal(aiView.aiConfig.enabled,false);assert.equal(aiView.ai.installed,false);assert(!JSON.stringify(aiView).includes('private-ai-token'));assert(!('secret' in aiView.aiConfig));
  assert.equal((await saveAI({provider:'openai',model:'stub-only',enabled:true})).status,200);assert.equal((await saveAI({provider:'openai',model:'stub-only',enabled:false})).status,200);assert.equal((await context('live')).decrypt((await context('live')).get('ai','config').secret).token,'private-ai-token','disabling AI must preserve its encrypted key');
  assert.equal((await saveAI({provider:'anthropic',model:'stub-only',enabled:false})).status,400,'changing providers requires a new key');assert.equal((await saveAI({provider:'openai',model:'stub-only',enabled:'false'})).status,400);
  const calls=providerCalls,replay=await callback(req('/api/social/x?code=test-code&state='+flow.state,undefined,'nh_access=owner; nh_social='+cookie),route);assert.match(replay.headers.get('location')!,/social=failed/);assert.equal(providerCalls,calls);
  await ctx.put('channel',account.id,{...account,secret:ctx.encrypt({...ctx.decrypt(account.secret),expiresAt:new Date(Date.now()+1000).toISOString()})});
  const post={service:'tistory',channel:'x',title:'동시 게시 검증',body:'외부 전송 금지',status:'scheduled',account:account.id,scheduledAt:new Date().toISOString()};await ctx.put('content','race-check',post);const stale=await controller({});
  await ctx.put('content','race-check',{...post,status:'published',externalId:'already-published'});
  const duplicate=await stale.handle(req('/api/dashboard/content/publish',{}),'/api/content/publish',{id:'race-check'},owner.email);assert.equal(duplicate.status,409);assert.equal((await context('live')).get('content','race-check').externalId,'already-published','refresh reload must never restore an older scheduled post');
  const live=await context('live'),plan={service:'tistory',business:'platform',topic:'중단할 자동 기획',enabled:true,autoPublish:true,nextAt:new Date(0).toISOString(),days:7,channels:['x']};await live.put('plan','disabled-queued-plan',plan);await live.put('plan','disable-during-generation',plan);await live.put('ai','config',{enabled:true,provider:'openai',model:'stub-only',secret:live.encrypt({token:'no-real-ai-call'})});
  await live.put('prompt','tistory:all',{service:'tistory',business:'external-business',instructions:'FOREIGN_BASE_INSTRUCTIONS'});await live.put('prompt','tistory:x',{service:'tistory',business:'external-business',tone:'FOREIGN_CHANNEL_TONE',instructions:'FOREIGN_CHANNEL_INSTRUCTIONS'});
  let aiCalls=0,aiPrompt='';const oauthFetch=globalThis.fetch;globalThis.fetch=async(input,init)=>{if(String(input)!=='https://api.openai.com/v1/chat/completions')return oauthFetch(input,init);aiCalls++;aiPrompt=JSON.parse(String(init?.body)).messages[0].content;const concurrent=await context('live');for(const id of ['disable-during-generation','disabled-queued-plan'])await concurrent.put('plan',id,{...concurrent.get('plan',id),enabled:false});return Response.json({choices:[{message:{content:JSON.stringify({title:'중단 중 생성된 초안',x:'공개 테스트 자료'})}}]});};
  let workerError;try{await (await controller({})).tick();}catch(e){workerError=e;}finally{globalThis.fetch=oauthFetch;}
  const afterGeneration=await context('live'),generation=afterGeneration.list('generation').find((g:{planId:string;ids:string[]})=>['disable-during-generation','disabled-queued-plan'].includes(g.planId));assert(generation&&generation.ids.length===1);assert.equal(afterGeneration.get('plan','disable-during-generation').enabled,false);assert.equal(afterGeneration.get('content',generation.ids[0]).status,'draft','disabling the plan during AI generation must prevent automatic scheduling');assert.equal(workerError,undefined);assert.equal(aiCalls,1,'another plan disabled during this generation must not be revived from the queued snapshot');assert.equal(afterGeneration.get('plan','disabled-queued-plan').enabled,false);assert(!aiPrompt.includes('FOREIGN_'),'legacy non-platform prompt rules must never enter AI requests');assert(!aiPrompt.includes('"facebook"')&&!aiPrompt.includes('"linkedin"')&&!aiPrompt.includes('"pinterest"'),'AI must only request selected channels');
  await afterGeneration.put('plan','unchanged-plan',plan);globalThis.fetch=async(input,init)=>String(input)==='https://api.openai.com/v1/chat/completions'?Response.json({choices:[{message:{content:JSON.stringify({title:'변경되지 않은 자동 기획',x:'공개 테스트 자료'})}}]}):oauthFetch(input,init);try{await (await controller({})).tick();}finally{globalThis.fetch=oauthFetch;}
  const automatic=await context('live'),automaticGeneration=automatic.list('generation').find((g:{planId:string;ids:string[]})=>g.planId==='unchanged-plan');assert(automaticGeneration?.ids.length===1);assert.equal(automatic.get('content',automaticGeneration.ids[0]).status,'scheduled','an unchanged approved plan must auto-schedule after JSONB reload');assert.equal((await (await controller({})).handle(req('/api/dashboard/content/cancel',{}),'/api/content/cancel',{id:automaticGeneration.ids[0]},owner.email)).status,200);await automatic.put('plan','unchanged-plan',{...automatic.get('plan','unchanged-plan'),enabled:false});
  await afterGeneration.put('content','publish-timeout',post);let publishCalls=0;globalThis.fetch=async(input,init)=>{if(String(input)!=='https://api.x.com/2/tweets')return oauthFetch(input,init);publishCalls++;if(publishCalls===1)throw new Error('stub response timed out');return Response.json({data:{id:'98765'}});};
  try{
   const action=async(path:string,payload:Record<string,unknown>)=>(await controller({})).handle(req('/api/dashboard/'+path,{}),'/api/'+path,payload,owner.email);
   assert.equal((await action('content/publish',{id:'publish-timeout'})).status,502);let uncertain=(await context('live')).get('content','publish-timeout');assert.equal(uncertain.status,'review');assert.equal(uncertain.uncertain,true);
   assert.equal((await action('content/publish',{id:'publish-timeout'})).status,400);await (await controller({})).tick();assert.equal(publishCalls,1,'cron must never retry a timed-out external write automatically');
   assert.equal((await action('content/cancel',{id:'publish-timeout'})).status,200);uncertain=(await context('live')).get('content','publish-timeout');assert.equal(uncertain.status,'review');assert.equal(uncertain.uncertain,true);
   assert.equal((await action('content/schedule',{id:'publish-timeout',account:account.id})).status,400);assert.equal((await action('content/schedule',{id:'publish-timeout',account:account.id,checked:true})).status,200);
   const first=await controller({}),competing=await controller({});assert.equal((await first.handle(req('/api/dashboard/content/publish',{}),'/api/content/publish',{id:'publish-timeout'},owner.email)).status,200);assert.equal((await competing.handle(req('/api/dashboard/content/publish',{}),'/api/content/publish',{id:'publish-timeout'},owner.email)).status,409);assert.equal(publishCalls,2,'a stale publisher must lose CAS before another external write');
  }finally{globalThis.fetch=oauthFetch;}
  const content=await (await controller({demo:true})).handle(req('/api/dashboard/sample/content',{}),'/api/content',{service:'tistory',channel:'blog',blogTarget:'wordpress',title:'SNS WordPress 초안',body:'공개 테스트 자료'},owner.email);assert.equal(content.status,200);assert.equal((await content.json()).contents[0].blogTarget,'wordpress');
  const sample=await context('sample'),legacyPost={service:'crm',business:'platform',channel:'x',title:'과거 기록',body:'조회만 유지',status:'scheduled',scheduledAt:new Date(0).toISOString()},legacyPlan={service:'crm',business:'platform',topic:'과거 반복 기획',enabled:true,autoPublish:true,nextAt:new Date(0).toISOString(),days:7,channels:['x']};await sample.put('content','legacy-crm',legacyPost);await sample.put('plan','legacy-crm',legacyPlan);
  const independent=await controller({demo:true});for(const path of ['content','content/generate','plan','prompt','channel'])assert.equal((await independent.handle(req('/api/dashboard/sample/'+path,{}),'/api/'+path,{service:'crm',business:'platform'},owner.email)).status,400,path+' must reject another service');
  assert.equal((await independent.handle(req('/api/dashboard/sample/studio/duplicate',{}),'/api/studio/duplicate',{id:'legacy-crm'},owner.email)).status,400);assert.equal((await independent.handle(req('/api/dashboard/sample/content/cancel',{}),'/api/content/cancel',{id:'legacy-crm'},owner.email)).status,400);
  const oldPublishing={...legacyPost,status:'publishing',startedAt:new Date(0).toISOString()},oldGeneration={service:'crm',business:'platform',status:'running',startedAt:new Date(0).toISOString()},oldPublished={...legacyPost,status:'published',externalId:'legacy-id'},oldAccount={service:'crm',channel:'x',userId:account.userId,verifiedAt:account.verifiedAt,label:'조회 전용 과거 계정',secret:sample.encrypt({...ctx.decrypt(account.secret),expiresAt:new Date(0).toISOString()})};await sample.put('content','legacy-publishing',oldPublishing);await sample.put('content','legacy-published',oldPublished);await sample.put('generation','legacy-generation',oldGeneration);await sample.put('channel','legacy-account',oldAccount);
  const isolated=await controller({demo:true});for(const [path,id] of [['content/check','legacy-published'],['channel/verify','legacy-account']])assert.equal((await isolated.handle(req('/api/dashboard/sample/'+path,{}),'/api/'+path,{id},owner.email)).status,400);await isolated.tick();const after=await context('sample');assert.deepEqual(after.get('content','legacy-crm'),legacyPost);assert.deepEqual(after.get('content','legacy-publishing'),oldPublishing);assert.deepEqual(after.get('generation','legacy-generation'),oldGeneration);assert.deepEqual(after.get('plan','legacy-crm'),legacyPlan);assert.deepEqual(after.get('channel','legacy-account'),oldAccount);assert(after.list('source').length===0,'isolation test must not collect other service data');
  const legacyLive=await context('live');await legacyLive.put('channel','legacy-account',oldAccount);const beforeLegacyTick=providerCalls;await (await controller({})).tick();assert.equal(providerCalls,beforeLegacyTick,'worker must never rotate another service account');assert.deepEqual((await context('live')).get('channel','legacy-account'),oldAccount);
 }finally{globalThis.fetch=previousFetch;g.nhPool=previousPool;await db.close();for(const key of Object.keys(process.env))if(!(key in previousEnv))delete process.env[key];Object.assign(process.env,previousEnv);}
});
