'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const handlers={},calls=[],saved=[];
const context={window:{addEventListener(){}},document:{addEventListener:(name,fn)=>handlers[name]=fn},session:{readOnly:false},state:{month:'2026-10',scope:'all'},labels:{instagram:'인스타그램',threads:'Threads'},data:{growthCampaigns:[{id:'a',service:'tistory',model:'audience',name:'<성장>',goal:'공유 비교'}],growthResults:[]},esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),formField:(l,n,v,t,x)=>`<label>${l}<input name="${n}" type="${t}" value="${v}" ${x}></label>`,selectField:()=>'',today:()=> '2026-10-08',won:n=>n+'원',render(){},toast(){},download:(...v)=>calls.push(v)};
vm.createContext(context);
context.document.getElementById=()=>null;
context.FormData=class{constructor(form){this.form=form;}[Symbol.iterator](){return Object.entries(this.form.values)[Symbol.iterator]();}};
context.api=async(route,value)=>{saved.push({route,value});return context.data;};
vm.runInContext(fs.readFileSync('public/one/app.js','utf8').split(/\r?\n/).filter(l=>/^const (effectiveAt|publicationTimeLabel)=/.test(l)).join('\n'),context);
vm.runInContext(fs.readFileSync('public/one/studio.js','utf8'),context);
Object.assign(context,{dateKey:v=>String(v||'').slice(0,10),dt:v=>v,serviceName:v=>v,statusLabels:{published:'게시 완료',scheduled:'예약 대기'}});
context.data.contents=[{id:'m',service:'tistory',channel:'instagram',title:'manual-october',status:'published',manual:true,registeredAt:'2026-10-08T03:50:00Z',publishedAt:'2026-09-30T01:00:00Z'},{id:'a',service:'tistory',channel:'instagram',title:'api-september',status:'published',publishedAt:'2026-09-30T01:00:00Z',registeredAt:'2026-10-08T03:50:00Z'},{id:'s',service:'tistory',channel:'threads',title:'scheduled-october',status:'scheduled',scheduledAt:'2026-10-09T10:30:00Z',createdAt:'2026-09-01T00:00:00Z'}];
let calendar=context.window.NuriStudio.render('calendar');
assert(calendar.includes('manual-october')&&calendar.includes('URL 등록'));
assert(calendar.includes('2026-10-08T03:50:00Z KST')&&!calendar.includes('api-september'));
assert(calendar.includes('scheduled-october')&&calendar.includes('예약'));
context.state.month='2026-09';calendar=context.window.NuriStudio.render('calendar');
assert(calendar.includes('api-september')&&!calendar.includes('manual-october')&&!calendar.includes('scheduled-october'));
assert.equal(vm.runInContext("publicationTimeLabel({manual:true})",context),'URL 등록 시각');
assert.equal(vm.runInContext("effectiveAt({status:'published',manual:true,publishedAt:'legacy'})",context),'legacy');
context.state.month='2026-10';
let html=context.window.NuriStudio.render('growth');
assert(html.includes('계정 성장'));assert(html.includes('&lt;성장&gt;'));assert(!html.includes('value="undefined"'));
assert(html.includes('<strong>미확인</strong>'));assert(!/name="url"[^>]*required/.test(html));
const financeFields=['impressions','clicks','leads','orders','revenue','cost'],metric=(html,label)=>html.split('<span>'+label+'</span><strong>')[1].split('</strong>')[0];
for(const label of ['기록 수익','기록 비용','기록 수익 − 비용','수익 / 비용','CTR','주문 / 클릭'])assert.equal(metric(html,label),'미확인','empty records must not imply zero or a known ratio');
for(const field of financeFields){assert(new RegExp('name="'+field+'"[^>]*value=""').test(html));assert(!new RegExp('name="'+field+'"[^>]*required').test(html));}
context.data.growthResults=[{id:'r',campaignId:'a',service:'tistory',day:'2026-10-08',channel:'instagram',views:0,follows:null,shares:2,saves:null,note:'=SUM(A1)'}];
html=context.window.NuriStudio.render('growth');
assert(html.includes('<strong>0</strong><small>확인분 합계 · 1/1건'));
assert(html.includes('<strong>미확인</strong><small>확인분 합계 · 0/1건'));
(async()=>{
 const click=async(action,id)=>handlers.click({target:{closest:()=>({dataset:{studio:action,id},isConnected:false})},preventDefault(){}});
 await click('growth-csv');assert.equal(calls.length,1);let csv=calls[0][1];assert(csv.includes('"조회 수"'));assert(csv.includes('"0","","","","","","","2",""'));assert(csv.includes('"\'=SUM(A1)"'));assert(csv.includes('"2","","","","","","","","\'=SUM(A1)"'),'unknown finance fields export as blanks');
 const known={...context.data.growthResults[0],impressions:100,clicks:10,leads:2,orders:1,revenue:1000,cost:100};
 context.data.growthResults=[known,{...known,id:'partial',day:'2026-10-09',impressions:null,clicks:5,orders:0,revenue:2000,cost:null}];html=context.window.NuriStudio.render('growth');
 assert.equal(metric(html,'기록 수익'),'3000원');assert.equal(metric(html,'기록 비용'),'100원');assert(html.includes('100원</strong><small>확인분 합계 · 1/2건'));
 for(const label of ['기록 수익 − 비용','수익 / 비용','CTR'])assert.equal(metric(html,label),'미확인','partial records cannot imply a complete profit or ratio');
 assert.equal(metric(html,'주문 / 클릭'),'6.7%','each ratio needs only its own two fully known fields');
 context.data.growthResults=[known];html=context.window.NuriStudio.render('growth');
 assert.equal(metric(html,'기록 수익 − 비용'),'900원');assert.equal(metric(html,'수익 / 비용'),'1000.0%');assert.equal(metric(html,'CTR'),'10.0%');assert.equal(metric(html,'주문 / 클릭'),'10.0%');
 context.data.growthResults=[{...known,...Object.fromEntries(financeFields.map(k=>[k,0]))}];await click('result-edit','r');html=context.window.NuriStudio.render('growth');
 for(const field of financeFields)assert(new RegExp('name="'+field+'"[^>]*value="0"').test(html),'editing must preserve a confirmed zero');
 assert.equal(metric(html,'기록 수익 − 비용'),'0원');assert.equal(metric(html,'수익 / 비용'),'미정');assert.equal(metric(html,'CTR'),'미정');
 await click('growth-csv');assert(calls[1][1].includes('"0","0","0","0","0","0","\'=SUM(A1)"'),'confirmed finance zero exports as zero');
 const submit=async(values)=>handlers.submit({target:{matches:()=>true,dataset:{studioForm:'result'},querySelector:()=>({isConnected:false}),values},preventDefault(){}});
 const blank=Object.fromEntries([...financeFields,'views','reach','profileVisits','follows','unfollows','likes','replies','shares','saves'].map(k=>[k,'']));
 await submit({id:'',version:'1',campaignId:'a',day:'2026-10-08',channel:'instagram',...blank});assert.equal(saved[0].route,'growth/result');for(const field of Object.keys(blank))assert.equal(saved[0].value[field],null,'blank form values must save as unknown');
 await submit({id:'r',version:'2',campaignId:'a',day:'2026-10-08',channel:'instagram',...blank,revenue:'0',cost:'100'});assert.equal(saved[1].value.revenue,0);assert.equal(saved[1].value.cost,100);assert.equal(saved[1].value.clicks,null);assert.equal(saved[1].value.version,2);
 const notices=[],copies=[];let finishPreview,clipboardStarted=false,previewCalls=0;
 Object.assign(context,{Blob,ClipboardItem:class{constructor(items){this.items=items;}},DOMParser:class{parseFromString(html,type){assert.equal(type,'text/html');assert.equal(html,'<h2>검증 &lt;본문&gt;</h2><p>서식만 복사</p>');return {body:{textContent:'검증 <본문>서식만 복사'}};}},toast:v=>notices.push(v)});
 context.navigator={clipboard:{write:async items=>{clipboardStarted=true;assert.equal(items.length,1);const blobs=await Promise.all(Object.entries(items[0].items).map(async([type,p])=>{const blob=await p;assert.equal(blob.type,type);return [type,await blob.text()];}));copies.push(Object.fromEntries(blobs));},writeText:async text=>copies.push(text)}};
 context.state.page='studio';context.data.contents.push({id:'copy',service:'tistory',channel:'blog',title:'제목은 별도',body:'## 검증 <본문>\n\n서식만 복사',status:'published'});context.labels.blog='블로그';context.window.NuriStudio.open('copy');
 context.api=async()=>{previewCalls++;return new Promise(resolve=>finishPreview=resolve);};
 const pending=click('copy-rich');assert(clipboardStarted,'clipboard write must start before awaiting the preview, preserving click activation');
 finishPreview({html:'<h2>검증 &lt;본문&gt;</h2><p>서식만 복사</p>',document:'<!doctype html><title>제목은 별도</title>',analysis:{}});await pending;
 assert.equal(copies[0]['text/html'],'<h2>검증 &lt;본문&gt;</h2><p>서식만 복사</p>');assert.equal(copies[0]['text/plain'],'검증 <본문>서식만 복사');assert(!copies[0]['text/html'].includes('<title>'));assert(notices.at(-1).includes('기본모드'));
 await click('copy-html');assert.equal(copies[1],copies[0]['text/html']);assert(notices.at(-1).includes('HTML 모드에서만'));assert.equal(previewCalls,1,'source copy reuses the same safe preview');
 const writes=copies.length;context.ClipboardItem=undefined;await click('copy-rich');assert.equal(copies.length,writes);assert(notices.at(-1).includes('지원하지 않는'));assert.equal(previewCalls,1);
 context.ClipboardItem=class{constructor(items){this.items=items;}};context.navigator.clipboard.write=async()=>{throw Error('복사 권한 거부');};await click('copy-rich');assert.equal(notices.at(-1),'복사 권한 거부');assert.equal(copies.length,writes);
 context.session.readOnly=true;await click('copy-rich');await click('copy-html');assert.equal(notices.at(-1),'보기 전용 계정입니다.');assert.equal(copies.length,writes);context.session.readOnly=false;
 Object.assign(context,{adsensePanel:()=>'',service:()=>({}),money:v=>v==null?'미확인':String(v),button:()=>'',table:(_headers,rows)=>rows.join(''),row:cells=>cells.join('|'),notice:v=>v,disclosure:()=>'',empty:()=>''});
 const query={keys:['partial-query'],clicks:null,impressions:null,ctr:null,position:null};
 context.data.google={configured:true,reports:[{month:'2026-10',ga:null,search:null,queries:[query]}]};
 vm.runInContext(fs.readFileSync('public/one/app.js','utf8').split(/\r?\n/).find(l=>/^function traffic\(/.test(l)),context);
 html=vm.runInContext('traffic()',context);assert(html.includes('partial-query|미확인|미확인|미확인|미확인'));assert(!html.includes('0.00%'));
 Object.assign(query,{clicks:0,impressions:1,ctr:0,position:1.2});html=vm.runInContext('traffic()',context);assert(html.includes('partial-query|0|1|0.00%|1.2'));
 console.log('studio growth: unknown/zero, partial/known finance, form save, escaped rendering, CSV and incomplete search rows passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
