"use client";
import {useEffect,useId,useState} from 'react';
import type {Order,OrderPage,Shipment} from '@/lib/types';
import {carrierLabels,fulfillmentLabels,money,paymentLabels} from '@/lib/types';
import {Modal} from './market';
import {Icon} from './icons';
import {InquiryReply} from './admin-inquiries';

const methods={CARD:'카드',NAVERPAY:'네이버페이',KAKAOPAY:'카카오페이',VIRTUAL_ACCOUNT:'가상계좌'};
const claimTypes={CANCEL:'취소',RETURN:'반품',EXCHANGE:'교환'};
const claimStates={REQUESTED:'접수',APPROVED:'승인',REJECTED:'반려',COMPLETED:'완료'};
const shipmentStates={LABEL_REGISTERED:'송장 등록 · 인수 전',SHIPPED:'배송중',DELIVERED:'배송 완료'};
const date=(value:string)=>new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
type Mutate=(body:unknown,success?:string)=>Promise<boolean>;
function canPrepare(order:Order){return ['PAID','PARTIALLY_REFUNDED'].includes(order.paymentStatus)&&order.fulfillmentStatus==='UNFULFILLED'&&!order.claims.some(claim=>['REQUESTED','APPROVED'].includes(claim.status));}
async function read<T>(url:string,signal:AbortSignal):Promise<T>{const response=await fetch(url,{signal,cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error??'주문 정보를 불러오지 못했습니다.');return result;}

function ShipmentAction({shipment,order,busy,mutate}:{shipment:Shipment;order:Order;busy:boolean;mutate:Mutate}){
 const reasonId=useId();
 const [open,setOpen]=useState(false),[reason,setReason]=useState(''),[failed,setFailed]=useState(false);
 const allowed=['PAID','PARTIALLY_REFUNDED'].includes(order.paymentStatus)&&(shipment.status!=='LABEL_REGISTERED'||!order.claims.some(c=>['REQUESTED','APPROVED'].includes(c.status)));
 if(shipment.status==='DELIVERED')return <span className="success-text">배달 확인 완료</span>;
 if(!allowed)return <span className="hint">결제·클레임 처리 후 진행</span>;
 const pickup=shipment.status==='LABEL_REGISTERED';
 return <div className="shipment-action">{!open?<button className="secondary compact" disabled={busy} onClick={()=>setOpen(true)}>{pickup?'인수 확인':'배달 확인'}</button>:<form onSubmit={async e=>{e.preventDefault();setFailed(false);if(await mutate({action:'shipment.update',shipmentId:shipment.id,status:pickup?'SHIPPED':'DELIVERED',reason},pickup?'택배사 인수를 확인하고 발송 시각을 기록했습니다.':'배달 완료와 확인 시각을 기록했습니다.')){setOpen(false);setReason('');}else setFailed(true);}}>
  <div className="field"><label htmlFor={reasonId}>확인 근거</label><textarea id={reasonId} required maxLength={1000} rows={2} value={reason} onChange={e=>setReason(e.target.value)} placeholder={pickup?'기사님 인수 확인, 집하 스캔 등 실제 확인 근거':'택배사 배달 완료 조회, 고객 수령 확인 등'}/></div>
  <p className="hint">{pickup?'실제 택배사 인수가 확인된 뒤 저장해 주세요. 재고가 출고 처리됩니다.':'배달 완료를 확인한 뒤 저장해 주세요. 고객 주문 조회에 반영됩니다.'}</p>
  <div className="button-row"><button type="button" className="secondary compact" disabled={busy} onClick={()=>setOpen(false)}>취소</button><button className="primary compact" disabled={busy||!reason.trim()}>{pickup?'발송 확인 저장':'배송완료 저장'}</button></div>
  {failed&&<p role="alert" className="error-text">저장하지 못했습니다. 결제·클레임 상태와 상단 오류 안내를 확인해주세요.</p>}
 </form>}</div>;
}

function ShipmentRegister({order,busy,mutate}:{order:Order;busy:boolean;mutate:Mutate}){
 const fieldId=useId();
 const [carrier,setCarrier]=useState('CJ'),[tracking,setTracking]=useState(''),[failed,setFailed]=useState(false);
 const allowed=order.fulfillmentStatus==='PREPARING'&&['PAID','PARTIALLY_REFUNDED'].includes(order.paymentStatus)&&!order.claims.some(c=>['REQUESTED','APPROVED'].includes(c.status));
 if(!allowed)return null;
 return <form className="shipment-register" onSubmit={async e=>{e.preventDefault();setFailed(false);if(await mutate({action:'shipment.register',orderNumber:order.number,carrier,trackingNumber:tracking},'송장을 등록했습니다. 실제 인수 후 발송 확인을 저장해주세요.'))setTracking('');else setFailed(true);}}>
  <h4>개별 송장 등록</h4><div className="shipment-register-fields"><div className="field"><label htmlFor={`${fieldId}-carrier`}>택배사</label><select id={`${fieldId}-carrier`} value={carrier} onChange={e=>setCarrier(e.target.value)}>{Object.entries(carrierLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><div className="field"><label htmlFor={`${fieldId}-tracking`}>송장번호</label><input id={`${fieldId}-tracking`} required inputMode="numeric" maxLength={20} pattern="([0-9]|-){10,20}" value={tracking} onChange={e=>setTracking(e.target.value)} placeholder="숫자 10~14자리"/></div><button className="primary compact" disabled={busy||!tracking.trim()}>송장 등록</button></div>
  <p className="hint">송장 등록 → 택배사 인수 확인 → 배달 완료 순서로 기록합니다.</p>{failed&&<p className="error-text" role="alert">송장을 등록하지 못했습니다. 번호 중복·주문 상태와 상단 오류 안내를 확인해주세요.</p>}
 </form>;
}

export function OrderTable({orders,busy,onDetail,prepare}:{orders:Order[];busy:boolean;onDetail:(order:Order)=>void;prepare:(id:string)=>void}){
 return <><div className="table-wrap"><table className="orders-table"><thead><tr><th>주문번호 · 주문일</th><th>고객 · 상품</th><th>결제금액</th><th>결제 · 배송 상태</th><th>발송현황 · 송장</th><th>작업</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}>
  <td><button className="table-link" onClick={()=>onDetail(order)}>{order.number}</button><small>{date(order.createdAt)}</small>{order.isDemo&&<span className="tag">체험</span>}</td>
  <td><strong>{order.customer.name}</strong><small>{order.items[0]?.name}{order.items.length>1?` 외 ${order.items.length-1}종`:''}</small><small>{order.items.reduce((sum,item)=>sum+item.quantity,0)}개 · {methods[order.method]}</small></td>
  <td><strong>{money(order.total)}</strong>{order.refundTotal>0&&<small className="error-text">환불 {money(order.refundTotal)}</small>}</td>
  <td><span className={`tag ${order.paymentStatus==='PAID'?'blue':''}`}>{paymentLabels[order.paymentStatus]}</span><small>{fulfillmentLabels[order.fulfillmentStatus]}{order.purchaseStatus==='CONFIRMED'?' · 구매확정':''}</small>{order.claims.some(claim=>claim.status==='REQUESTED')&&<span className="tag claim-tag">요청 확인 필요</span>}</td>
  <td className="shipment-cell">{order.shipments.length?order.shipments.map(shipment=><div key={shipment.id}><strong className={shipment.status==='LABEL_REGISTERED'?'':'success-text'}>{shipment.status==='LABEL_REGISTERED'?'미발송 · 송장 등록':shipment.status==='SHIPPED'?'발송 완료 · 배송중':'발송 완료 · 배달 완료'}</strong><small>{carrierLabels[shipment.carrier]??shipment.carrier} · {shipment.trackingNumber}</small><small>{shipment.shippedAt?`발송 ${date(shipment.shippedAt)}`:shipment.status!=='LABEL_REGISTERED'?'발송 시각 미기록 (기존 이력)':'택배사 인수 전'}</small></div>):<span className="muted">{['PAID','PARTIALLY_REFUNDED'].includes(order.paymentStatus)?'미발송 · 송장 미등록':'발송 이력 없음'}</span>}{order.inquiries?.some(i=>!i.reply)&&<small className="error-text">미답변 문의 {order.inquiries.filter(i=>!i.reply).length}건</small>}</td>
  <td>{canPrepare(order)?<button className="secondary compact" disabled={busy} onClick={()=>prepare(order.id)}>출고 지시</button>:<button className="secondary compact" onClick={()=>onDetail(order)}>{['PREPARING','LABEL_REGISTERED','SHIPPED'].includes(order.fulfillmentStatus)?'배송 처리':'상세'}</button>}</td>
 </tr>)}</tbody></table></div>{!orders.length&&<div className="orders-empty"><Icon name="bag" size={30}/><strong>조건에 맞는 주문이 없습니다.</strong><p>검색어와 조회 기간을 확인해 주세요.</p></div>}</>;
}

export function OrderManager({revision,busy,onDetail,mutate,kind='all'}:{revision:unknown;busy:boolean;onDetail:(order:Order)=>void;mutate:Mutate;kind?:'all'|'shipments'|'claims'}){
 const [filters,setFilters]=useState({q:'',payment:'',fulfillment:'',from:'',to:'',scope:'all',claimStatus:'',shipping:'all'}),[draft,setDraft]=useState(''),[page,setPage]=useState(1),[result,setResult]=useState<OrderPage|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{
  let controller:AbortController;let active=true;
  const load=async()=>{controller?.abort();controller=new AbortController();const current=controller;setLoading(true);setError('');try{const next=await read<OrderPage>(`/api/admin/orders?${new URLSearchParams({...filters,page:String(page),kind})}`,controller.signal);if(active){setResult(next);if(next.page!==page)setPage(next.page);}}catch(e){if(active&&(e as Error).name!=='AbortError')setError((e as Error).message);}finally{if(active&&!current.signal.aborted)setLoading(false);}};
  void load();const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!busy)void load();},30000);return()=>{active=false;controller?.abort();clearInterval(timer);};
 },[filters,page,kind,revision,refresh,busy]);
 const change=(key:keyof typeof filters,value:string)=>{setFilters(previous=>({...previous,[key]:value}));setPage(1);};
 const totalPages=Math.max(1,Math.ceil((result?.total??0)/20));
 return <section className="admin-panel order-manager">
  <div className="panel-heading"><div><span className="eyebrow">ORDER CENTER</span><h2>{kind==='shipments'?'등록 송장':kind==='claims'?'취소·교환·반품 요청':'주문 목록'}</h2></div><button className="secondary compact" onClick={()=>setRefresh(value=>value+1)} disabled={loading}>조회 새로고침</button></div>
  {kind!=='claims'&&<div className="status-switches shipping-switches" aria-label="발송현황 필터">{([['all','전체'],['pending','발송 대기'],['label','송장 등록 · 인수 전'],['transit','배송중'],['delivered','배송완료']] as const).map(([key,label])=><button key={key} className={filters.shipping===key?'active':''} aria-pressed={filters.shipping===key} onClick={()=>change('shipping',key)}>{label}<strong>{result?.shippingCounts[key]??'—'}</strong></button>)}</div>}
  <form className="order-filters" onSubmit={e=>{e.preventDefault();change('q',draft.trim());}}>
   <label className="order-search"><Icon name="search" size={18}/><input aria-label="주문 검색" maxLength={100} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="주문번호, 고객명, 연락처, 상품, 송장번호"/></label><button className="primary compact">검색</button>
   <label>결제 상태<select aria-label="결제 상태 필터" value={filters.payment} onChange={e=>change('payment',e.target.value)}><option value="">전체 결제</option>{Object.entries(paymentLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
   <label>배송 상태<select aria-label="배송 상태 필터" value={filters.fulfillment} onChange={e=>change('fulfillment',e.target.value)}><option value="">전체 배송</option>{Object.entries(fulfillmentLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
   <label>주문 유형<select aria-label="주문 유형 필터" value={filters.scope} onChange={e=>change('scope',e.target.value)}><option value="all">전체 주문</option><option value="demo">체험 주문</option><option value="real">일반 주문</option></select></label>
   {kind==='claims'&&<label>요청 상태<select aria-label="요청 상태 필터" value={filters.claimStatus} onChange={e=>change('claimStatus',e.target.value)}><option value="">전체 요청</option>{Object.entries(claimStates).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}
   <label>시작일<input type="date" aria-label="주문 시작일" value={filters.from} onChange={e=>change('from',e.target.value)}/></label><label>종료일<input type="date" aria-label="주문 종료일" value={filters.to} onChange={e=>change('to',e.target.value)}/></label>
   <button type="button" className="text-button" onClick={()=>{setDraft('');setFilters({q:'',payment:'',fulfillment:'',from:'',to:'',scope:'all',claimStatus:'',shipping:'all'});setPage(1);}}>초기화</button>
  </form>
  <div className="order-list-meta"><strong>{loading?'조회 중…':`${kind==='all'?'조회 결과':'해당 주문'} ${error?'—':result?.total.toLocaleString()??'—'}건`}</strong><span>한국 시각 기준 · 주문 20건씩 표시 · 30초 자동 갱신</span></div>
  {error&&<p role="alert" className="error-text">{error}</p>}
  <div aria-busy={loading} className="order-results">{loading&&!result?<p role="status" className="order-loading">주문을 조회하고 있습니다…</p>:!error&&result&&(kind==='all'?<OrderTable orders={result.orders} busy={busy} onDetail={onDetail} prepare={orderId=>void mutate({action:'order.prepare',orderId},'배송 준비로 변경했습니다.')}/>:<div className="table-wrap"><table><thead><tr><th>주문</th><th>{kind==='shipments'?'택배사 · 송장번호':'유형 · 사유'}</th><th>상태</th><th>작업</th></tr></thead><tbody>{result.orders.flatMap(order=>kind==='shipments'?order.shipments.map(shipment=><tr key={shipment.id}><td><button className="table-link" onClick={()=>onDetail(order)}>{order.number}</button><small>{order.customer.name}</small></td><td>{carrierLabels[shipment.carrier]??shipment.carrier}<small>{shipment.trackingNumber}</small></td><td><strong>{shipmentStates[shipment.status]}</strong><small>등록 {date(shipment.createdAt)}</small>{shipment.shippedAt&&<small>발송 {date(shipment.shippedAt)}</small>}{shipment.deliveredAt&&<small>완료 {date(shipment.deliveredAt)}</small>}</td><td><ShipmentAction shipment={shipment} order={order} busy={busy} mutate={mutate}/></td></tr>):order.claims.filter(claim=>!filters.claimStatus||claim.status===filters.claimStatus).map(claim=><tr key={claim.id}><td><button className="table-link" onClick={()=>onDetail(order)}>{order.number}</button><small>{order.customer.name}</small></td><td>{claimTypes[claim.type]}<small>{claim.reason}</small>{claim.resolution&&<small>{claim.resolution}</small>}</td><td>{claimStates[claim.status]}</td><td>{claim.status==='REQUESTED'&&<div className="button-row">{['APPROVED','REJECTED'].map(status=><button key={status} className="secondary compact" disabled={busy} onClick={()=>{const reason=prompt(status==='APPROVED'?'승인 근거와 처리 안내를 입력해 주세요':'반려 근거를 입력해 주세요');if(reason?.trim())void mutate({action:'claim.resolve',claimId:claim.id,status,reason});}}>{status==='APPROVED'?'승인':'반려'}</button>)}</div>}</td></tr>))}</tbody></table>{!result.total&&<p className="table-empty">조회 결과가 없습니다.</p>}</div>)}</div>
  <div className="order-pagination"><span>{result?.total?`${(result.page-1)*20+1}–${Math.min(result.page*20,result.total)} / ${result.total}건`:'0건'}</span><nav aria-label="주문 페이지"><button className="secondary compact" disabled={page<=1||loading} onClick={()=>setPage(value=>value-1)}><Icon name="back" size={14}/>이전</button><strong>{result?.page??1} / {totalPages}</strong><button className="secondary compact" disabled={page>=totalPages||loading} onClick={()=>setPage(value=>value+1)}>다음<Icon name="arrow" size={14}/></button></nav></div>
 </section>;
}

export function AdminOrderDetail({id,revision,onClose,busy,mutate,mutationError}:{id:string;revision:unknown;onClose:()=>void;busy:boolean;mutate:Mutate;mutationError:string}){
 const [order,setOrder]=useState<Order|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true,controller:AbortController;const load=async()=>{controller?.abort();controller=new AbortController();try{const next=await read<Order>(`/api/admin/orders?id=${encodeURIComponent(id)}`,controller.signal);if(active){setOrder(next);setError('');}}catch(e){if(active&&(e as Error).name!=='AbortError')setError((e as Error).message);}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},30000);return()=>{active=false;controller?.abort();clearInterval(timer);};},[id,revision,refresh]);
 return <Modal title={order?`주문 ${order.number}`:'주문 상세'} onClose={onClose} wide>
  {(error||mutationError)&&<p className="error-text" role="alert">{error?`갱신 실패: ${error}`:mutationError}</p>}
  {!order?<p role="status">주문을 불러오는 중입니다.</p>:<div className="order-detail">
   <div className="order-detail-summary"><div><div className="button-row"><span className="tag blue">{paymentLabels[order.paymentStatus]}</span><span className="tag">{fulfillmentLabels[order.fulfillmentStatus]}</span><span className="tag">{order.purchaseStatus==='CONFIRMED'?'구매확정':'구매확정 전'}</span>{order.isDemo&&<span className="tag">체험 주문</span>}</div><p>주문일 {date(order.createdAt)} · 한국 시각</p></div><button className="secondary compact" onClick={()=>setRefresh(value=>value+1)}>상세 새로고침</button></div>
   <section><h3>주문 상품 <span>{order.items.reduce((sum,item)=>sum+item.quantity,0)}개</span></h3>{order.items.map(item=><article className="order-detail-item" key={item.id}><div><strong>{item.name}</strong><p>{item.variantLabel}</p><small>개당 {money(item.unitPrice)} × {item.quantity}개{item.discount>0?` · 할인 ${money(item.discount)}`:''}</small><small>출고 {item.shippedQty}개 · 환불 {item.refundedQty}개</small></div><strong>{money(item.total)}</strong></article>)}</section>
   <div className="order-detail-columns"><section><h3>결제 내역</h3><dl className="order-facts"><div><dt>결제 수단</dt><dd>{methods[order.method]}</dd></div><div><dt>상품 금액</dt><dd>{money(order.subtotal)}</dd></div><div><dt>할인 금액</dt><dd>−{money(order.discount)}</dd></div><div><dt>배송비</dt><dd>{money(order.shipping)}</dd></div><div className="fact-total"><dt>주문 결제금액</dt><dd>{money(order.total)}</dd></div><div><dt>누적 환불액</dt><dd className="error-text">{money(order.refundTotal)}</dd></div><div><dt>환불 반영 잔액</dt><dd>{money(order.total-order.refundTotal)}</dd></div></dl><p className="hint">대기·실패 주문의 금액은 결제 완료 매출이 아닙니다.</p>{order.dueAt&&<p className="hint">결제 기한 {date(order.dueAt)}</p>}{order.virtualAccount&&<p className="hint">{order.virtualAccount.bank} {order.virtualAccount.accountNumber}</p>}</section>
   <section><h3>수취인 · 배송지</h3><dl className="order-facts customer-facts"><div><dt>수취인</dt><dd>{order.customer.name}</dd></div><div><dt>연락처</dt><dd>{order.customer.phone}</dd></div><div><dt>이메일</dt><dd>{order.customer.email||'미입력'}</dd></div><div><dt>우편번호</dt><dd>{order.customer.postcode}</dd></div><div><dt>배송 주소</dt><dd>{order.customer.address}<br/>{order.customer.addressDetail}</dd></div><div><dt>배송 메모</dt><dd>{order.customer.note||'없음'}</dd></div></dl></section></div>
   <section><h3>배송 이력 <span>{order.shipments.length}건</span></h3><p className="hint">송장 등록만으로 발송 처리하지 않습니다. 택배사 인수와 배달 완료를 각각 확인해주세요.</p>{order.shipments.length?order.shipments.map(shipment=><article key={shipment.id} className="order-record shipping-record"><Icon name="box" size={20}/><div><strong>{shipment.carrier} · {shipment.trackingNumber}</strong><p>{carrierLabels[shipment.carrier]??shipment.carrier} · {shipmentStates[shipment.status]}</p><ol className="shipment-timeline"><li className="done"><span>송장 등록</span><small>{date(shipment.createdAt)}</small></li><li className={shipment.status!=='LABEL_REGISTERED'?'done':''}><span>{shipment.status==='LABEL_REGISTERED'?'인수 전 · 미발송':'택배사 인수 · 발송 완료'}</span><small>{shipment.shippedAt?date(shipment.shippedAt):shipment.status!=='LABEL_REGISTERED'?'발송 시각 미기록 (기존 이력)':'실제 인수 확인 대기'}</small></li><li className={shipment.status==='DELIVERED'?'done':''}><span>배달 완료</span><small>{shipment.deliveredAt?date(shipment.deliveredAt):'배달 확인 대기'}</small></li></ol><ShipmentAction shipment={shipment} order={order} busy={busy} mutate={mutate}/></div></article>):<p className="muted">등록된 송장이 없습니다.{canPrepare(order)?' 출고 지시 후 송장을 등록해주세요.':''}</p>}<ShipmentRegister order={order} busy={busy} mutate={mutate}/></section>
   <section><h3>취소 · 교환 · 반품 <span>{order.claims.length}건</span></h3>{order.claims.length?order.claims.map(claim=><article key={claim.id} className="order-record"><Icon name="shield" size={20}/><div><strong>{claimTypes[claim.type]} · {claimStates[claim.status]}</strong><p>{claim.reason}</p><small>{claim.items.map(line=>`${order.items.find(item=>item.id===line.itemId)?.name??line.itemId} ${line.quantity}개`).join(', ')}</small>{claim.resolution&&<p className="reply">처리 안내: {claim.resolution}</p>}<small>{date(claim.createdAt)}</small></div></article>):<p className="muted">접수된 요청이 없습니다.</p>}</section>
   <section><h3>고객 문의 <span>{order.inquiries?.length??0}건</span></h3>{order.inquiries?.length?order.inquiries.map(inquiry=><article className="order-record" key={inquiry.id}><div><strong>{inquiry.subject}</strong><p>{inquiry.content}</p><span className={`tag ${inquiry.reply?'blue':'claim-tag'}`}>{inquiry.reply?'답변완료':'미답변'}</span><small>접수 {date(inquiry.createdAt)}</small><InquiryReply inquiry={inquiry} busy={busy} mutate={mutate}/></div></article>):<p className="muted">접수된 문의가 없습니다.</p>}</section>
   {order.reviews?.length? <section><h3>상품 리뷰</h3>{order.reviews.map(review=><article className="order-record" key={review.id}><div><strong>{review.rating} / 5점 · {review.status==='PENDING'?'검수 대기':review.status==='APPROVED'?'승인':'반려'}</strong><p>{review.content}</p><small>{date(review.createdAt)}</small></div></article>)}</section>:null}
   <div className="order-detail-footer"><p>고객정보는 주문 처리 목적으로만 사용해 주세요.</p>{canPrepare(order)&&<button className="primary compact" disabled={busy} onClick={()=>void mutate({action:'order.prepare',orderId:order.id},'배송 준비로 변경했습니다.')}>출고 지시</button>}</div>
  </div>}
 </Modal>;
}
